// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="train_step_train_step,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.860000,HLS_SYN_LAT=29,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1440,HLS_SYN_LUT=3368,HLS_VERSION=2024_2}" *)

module train_step (
        ap_clk,
        ap_rst_n,
        leds_port,
        leds_port_ap_vld,
        W1_out_address0,
        W1_out_ce0,
        W1_out_we0,
        W1_out_d0,
        W1_out_address1,
        W1_out_ce1,
        W1_out_we1,
        W1_out_d1,
        W2_out_address0,
        W2_out_ce0,
        W2_out_we0,
        W2_out_d0,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 8;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [3:0] leds_port;
output   leds_port_ap_vld;
output  [4:0] W1_out_address0;
output   W1_out_ce0;
output   W1_out_we0;
output  [7:0] W1_out_d0;
output  [4:0] W1_out_address1;
output   W1_out_ce1;
output   W1_out_we1;
output  [7:0] W1_out_d1;
output  [1:0] W2_out_address0;
output   W2_out_ce0;
output   W2_out_we0;
output  [7:0] W2_out_d0;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

reg leds_port_ap_vld;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [7:0] img_pos_0;
wire   [7:0] img_pos_1;
wire   [7:0] img_pos_2;
wire   [7:0] img_pos_3;
wire   [7:0] img_pos_4;
wire   [7:0] img_pos_5;
wire   [7:0] img_pos_6;
wire   [7:0] img_pos_7;
wire   [7:0] img_neg_0;
wire   [7:0] img_neg_1;
wire   [7:0] img_neg_2;
wire   [7:0] img_neg_3;
wire   [7:0] img_neg_4;
wire   [7:0] img_neg_5;
wire   [7:0] img_neg_6;
wire   [7:0] img_neg_7;
wire   [31:0] last_sample;
wire   [31:0] sample_idx;
reg   [1:0] W1_0_0;
reg   [1:0] W1_1_0;
reg   [1:0] W1_2_0;
reg   [1:0] W1_3_0;
reg   [1:0] W1_4_0;
reg   [1:0] W1_5_0;
reg   [1:0] W1_6_0;
reg   [1:0] W1_7_0;
reg   [1:0] W1_0_1;
reg   [1:0] W1_1_1;
reg   [1:0] W1_2_1;
reg   [1:0] W1_3_1;
reg   [1:0] W1_4_1;
reg   [1:0] W1_5_1;
reg   [1:0] W1_6_1;
reg   [1:0] W1_7_1;
reg   [1:0] W1_0_2;
reg   [1:0] W1_1_2;
reg   [1:0] W1_2_2;
reg   [1:0] W1_3_2;
reg   [1:0] W1_4_2;
reg   [1:0] W1_5_2;
reg   [1:0] W1_6_2;
reg   [1:0] W1_7_2;
reg   [1:0] W1_0_3;
reg   [1:0] W1_1_3;
reg   [1:0] W1_2_3;
reg   [1:0] W1_3_3;
reg   [1:0] W1_4_3;
reg   [1:0] W1_5_3;
reg   [1:0] W1_6_3;
reg   [1:0] W1_7_3;
reg   [7:0] train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_3;
reg   [7:0] train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_2;
reg   [7:0] train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_1;
reg   [7:0] train_mulmulmulstep_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed;
reg   [7:0] train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_7;
reg   [7:0] train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_6;
reg   [7:0] train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_5;
reg   [7:0] train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_4;
reg   [7:0] img_pos_0_read_reg_918;
reg   [7:0] img_pos_1_read_reg_924;
reg   [7:0] img_pos_2_read_reg_930;
reg   [7:0] img_pos_3_read_reg_936;
reg   [7:0] img_pos_4_read_reg_942;
reg   [7:0] img_pos_5_read_reg_948;
reg   [7:0] img_pos_6_read_reg_954;
reg   [7:0] img_pos_7_read_reg_960;
wire   [31:0] sub_ln145_fu_640_p2;
reg   [31:0] sub_ln145_reg_1006;
wire   [0:0] icmp_ln146_fu_646_p2;
reg   [0:0] icmp_ln146_reg_1011;
wire    ap_CS_fsm_state2;
reg   [3:0] trunc_ln1_reg_1021;
wire    ap_CS_fsm_state3;
wire   [7:0] grp_forwardHidden_fu_325_ap_return_0;
wire   [7:0] grp_forwardHidden_fu_325_ap_return_1;
wire   [7:0] grp_forwardHidden_fu_325_ap_return_2;
wire   [7:0] grp_forwardHidden_fu_325_ap_return_3;
wire   [7:0] grp_forwardHidden_fu_409_ap_return_0;
wire   [7:0] grp_forwardHidden_fu_409_ap_return_1;
wire   [7:0] grp_forwardHidden_fu_409_ap_return_2;
wire   [7:0] grp_forwardHidden_fu_409_ap_return_3;
wire    grp_updateHidden_fu_493_ap_start;
wire    grp_updateHidden_fu_493_ap_done;
wire    grp_updateHidden_fu_493_ap_idle;
wire    grp_updateHidden_fu_493_ap_ready;
wire   [1:0] grp_updateHidden_fu_493_W1_0_0_o;
wire    grp_updateHidden_fu_493_W1_0_0_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_1_0_o;
wire    grp_updateHidden_fu_493_W1_1_0_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_2_0_o;
wire    grp_updateHidden_fu_493_W1_2_0_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_3_0_o;
wire    grp_updateHidden_fu_493_W1_3_0_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_4_0_o;
wire    grp_updateHidden_fu_493_W1_4_0_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_5_0_o;
wire    grp_updateHidden_fu_493_W1_5_0_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_6_0_o;
wire    grp_updateHidden_fu_493_W1_6_0_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_7_0_o;
wire    grp_updateHidden_fu_493_W1_7_0_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_0_1_o;
wire    grp_updateHidden_fu_493_W1_0_1_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_1_1_o;
wire    grp_updateHidden_fu_493_W1_1_1_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_2_1_o;
wire    grp_updateHidden_fu_493_W1_2_1_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_3_1_o;
wire    grp_updateHidden_fu_493_W1_3_1_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_4_1_o;
wire    grp_updateHidden_fu_493_W1_4_1_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_5_1_o;
wire    grp_updateHidden_fu_493_W1_5_1_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_6_1_o;
wire    grp_updateHidden_fu_493_W1_6_1_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_7_1_o;
wire    grp_updateHidden_fu_493_W1_7_1_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_0_2_o;
wire    grp_updateHidden_fu_493_W1_0_2_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_1_2_o;
wire    grp_updateHidden_fu_493_W1_1_2_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_2_2_o;
wire    grp_updateHidden_fu_493_W1_2_2_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_3_2_o;
wire    grp_updateHidden_fu_493_W1_3_2_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_4_2_o;
wire    grp_updateHidden_fu_493_W1_4_2_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_5_2_o;
wire    grp_updateHidden_fu_493_W1_5_2_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_6_2_o;
wire    grp_updateHidden_fu_493_W1_6_2_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_7_2_o;
wire    grp_updateHidden_fu_493_W1_7_2_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_0_3_o;
wire    grp_updateHidden_fu_493_W1_0_3_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_1_3_o;
wire    grp_updateHidden_fu_493_W1_1_3_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_2_3_o;
wire    grp_updateHidden_fu_493_W1_2_3_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_3_3_o;
wire    grp_updateHidden_fu_493_W1_3_3_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_4_3_o;
wire    grp_updateHidden_fu_493_W1_4_3_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_5_3_o;
wire    grp_updateHidden_fu_493_W1_5_3_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_6_3_o;
wire    grp_updateHidden_fu_493_W1_6_3_o_ap_vld;
wire   [1:0] grp_updateHidden_fu_493_W1_7_3_o;
wire    grp_updateHidden_fu_493_W1_7_3_o_ap_vld;
wire    grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_start;
wire    grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_done;
wire    grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_idle;
wire    grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_ready;
wire   [4:0] grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_address0;
wire    grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_ce0;
wire    grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_we0;
wire   [7:0] grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_d0;
wire   [4:0] grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_address1;
wire    grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_ce1;
wire    grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_we1;
wire   [7:0] grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_d1;
wire    grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_start;
wire    grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_done;
wire    grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_idle;
wire    grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_ready;
wire   [1:0] grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_W2_out_address0;
wire    grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_W2_out_ce0;
wire    grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_W2_out_we0;
wire   [7:0] grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_W2_out_d0;
reg    grp_updateHidden_fu_493_ap_start_reg;
wire    ap_CS_fsm_state6;
reg   [11:0] ap_NS_fsm;
wire    ap_NS_fsm_state7;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [31:0] grp_fu_629_p0;
wire   [33:0] grp_fu_629_p1;
wire   [31:0] shl_ln145_fu_634_p2;
wire   [41:0] grp_fu_629_p2;
wire   [3:0] xor_ln146_fu_666_p2;
reg    ap_block_state12_on_subcall_done;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire   [41:0] grp_fu_629_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 W1_0_0 = 2'd0;
#0 W1_1_0 = 2'd0;
#0 W1_2_0 = 2'd0;
#0 W1_3_0 = 2'd0;
#0 W1_4_0 = 2'd0;
#0 W1_5_0 = 2'd0;
#0 W1_6_0 = 2'd0;
#0 W1_7_0 = 2'd0;
#0 W1_0_1 = 2'd0;
#0 W1_1_1 = 2'd0;
#0 W1_2_1 = 2'd0;
#0 W1_3_1 = 2'd0;
#0 W1_4_1 = 2'd0;
#0 W1_5_1 = 2'd0;
#0 W1_6_1 = 2'd0;
#0 W1_7_1 = 2'd0;
#0 W1_0_2 = 2'd0;
#0 W1_1_2 = 2'd0;
#0 W1_2_2 = 2'd0;
#0 W1_3_2 = 2'd0;
#0 W1_4_2 = 2'd0;
#0 W1_5_2 = 2'd0;
#0 W1_6_2 = 2'd0;
#0 W1_7_2 = 2'd0;
#0 W1_0_3 = 2'd0;
#0 W1_1_3 = 2'd0;
#0 W1_2_3 = 2'd0;
#0 W1_3_3 = 2'd0;
#0 W1_4_3 = 2'd0;
#0 W1_5_3 = 2'd0;
#0 W1_6_3 = 2'd0;
#0 W1_7_3 = 2'd0;
#0 train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_3 = 8'd0;
#0 train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_2 = 8'd0;
#0 train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_1 = 8'd0;
#0 train_mulmulmulstep_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed = 8'd0;
#0 train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_7 = 8'd0;
#0 train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_6 = 8'd0;
#0 train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_5 = 8'd0;
#0 train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_4 = 8'd0;
#0 grp_updateHidden_fu_493_ap_start_reg = 1'b0;
#0 grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_start_reg = 1'b0;
#0 grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_start_reg = 1'b0;
end

train_step_forwardHidden grp_forwardHidden_fu_325(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .input_0_val(img_pos_0),
    .input_1_val(img_pos_1),
    .input_2_val(img_pos_2),
    .input_3_val(img_pos_3),
    .input_4_val(img_pos_4),
    .input_5_val(img_pos_5),
    .input_6_val(img_pos_6),
    .input_7_val(img_pos_7),
    .W1_0_0(W1_0_0),
    .W1_1_0(W1_1_0),
    .W1_2_0(W1_2_0),
    .W1_3_0(W1_3_0),
    .W1_4_0(W1_4_0),
    .W1_5_0(W1_5_0),
    .W1_6_0(W1_6_0),
    .W1_7_0(W1_7_0),
    .W1_0_1(W1_0_1),
    .W1_1_1(W1_1_1),
    .W1_2_1(W1_2_1),
    .W1_3_1(W1_3_1),
    .W1_4_1(W1_4_1),
    .W1_5_1(W1_5_1),
    .W1_6_1(W1_6_1),
    .W1_7_1(W1_7_1),
    .W1_0_2(W1_0_2),
    .W1_1_2(W1_1_2),
    .W1_2_2(W1_2_2),
    .W1_3_2(W1_3_2),
    .W1_4_2(W1_4_2),
    .W1_5_2(W1_5_2),
    .W1_6_2(W1_6_2),
    .W1_7_2(W1_7_2),
    .W1_0_3(W1_0_3),
    .W1_1_3(W1_1_3),
    .W1_2_3(W1_2_3),
    .W1_3_3(W1_3_3),
    .W1_4_3(W1_4_3),
    .W1_5_3(W1_5_3),
    .W1_6_3(W1_6_3),
    .W1_7_3(W1_7_3),
    .ap_return_0(grp_forwardHidden_fu_325_ap_return_0),
    .ap_return_1(grp_forwardHidden_fu_325_ap_return_1),
    .ap_return_2(grp_forwardHidden_fu_325_ap_return_2),
    .ap_return_3(grp_forwardHidden_fu_325_ap_return_3)
);

train_step_forwardHidden grp_forwardHidden_fu_409(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .input_0_val(img_neg_0),
    .input_1_val(img_neg_1),
    .input_2_val(img_neg_2),
    .input_3_val(img_neg_3),
    .input_4_val(img_neg_4),
    .input_5_val(img_neg_5),
    .input_6_val(img_neg_6),
    .input_7_val(img_neg_7),
    .W1_0_0(W1_0_0),
    .W1_1_0(W1_1_0),
    .W1_2_0(W1_2_0),
    .W1_3_0(W1_3_0),
    .W1_4_0(W1_4_0),
    .W1_5_0(W1_5_0),
    .W1_6_0(W1_6_0),
    .W1_7_0(W1_7_0),
    .W1_0_1(W1_0_1),
    .W1_1_1(W1_1_1),
    .W1_2_1(W1_2_1),
    .W1_3_1(W1_3_1),
    .W1_4_1(W1_4_1),
    .W1_5_1(W1_5_1),
    .W1_6_1(W1_6_1),
    .W1_7_1(W1_7_1),
    .W1_0_2(W1_0_2),
    .W1_1_2(W1_1_2),
    .W1_2_2(W1_2_2),
    .W1_3_2(W1_3_2),
    .W1_4_2(W1_4_2),
    .W1_5_2(W1_5_2),
    .W1_6_2(W1_6_2),
    .W1_7_2(W1_7_2),
    .W1_0_3(W1_0_3),
    .W1_1_3(W1_1_3),
    .W1_2_3(W1_2_3),
    .W1_3_3(W1_3_3),
    .W1_4_3(W1_4_3),
    .W1_5_3(W1_5_3),
    .W1_6_3(W1_6_3),
    .W1_7_3(W1_7_3),
    .ap_return_0(grp_forwardHidden_fu_409_ap_return_0),
    .ap_return_1(grp_forwardHidden_fu_409_ap_return_1),
    .ap_return_2(grp_forwardHidden_fu_409_ap_return_2),
    .ap_return_3(grp_forwardHidden_fu_409_ap_return_3)
);

train_step_updateHidden grp_updateHidden_fu_493(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_updateHidden_fu_493_ap_start),
    .ap_done(grp_updateHidden_fu_493_ap_done),
    .ap_idle(grp_updateHidden_fu_493_ap_idle),
    .ap_ready(grp_updateHidden_fu_493_ap_ready),
    .input_0_val(img_pos_0_read_reg_918),
    .input_1_val(img_pos_1_read_reg_924),
    .input_2_val(img_pos_2_read_reg_930),
    .input_3_val(img_pos_3_read_reg_936),
    .input_4_val(img_pos_4_read_reg_942),
    .input_5_val(img_pos_5_read_reg_948),
    .input_6_val(img_pos_6_read_reg_954),
    .input_7_val(img_pos_7_read_reg_960),
    .train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_3(train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_3),
    .train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_7(train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_7),
    .W1_0_0_i(W1_0_0),
    .W1_0_0_o(grp_updateHidden_fu_493_W1_0_0_o),
    .W1_0_0_o_ap_vld(grp_updateHidden_fu_493_W1_0_0_o_ap_vld),
    .train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_2(train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_2),
    .train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_1(train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_1),
    .train_mulmulmulstep_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed(train_mulmulmulstep_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed),
    .train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_6(train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_6),
    .train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_5(train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_5),
    .train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_4(train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_4),
    .W1_1_0_i(W1_1_0),
    .W1_1_0_o(grp_updateHidden_fu_493_W1_1_0_o),
    .W1_1_0_o_ap_vld(grp_updateHidden_fu_493_W1_1_0_o_ap_vld),
    .W1_2_0_i(W1_2_0),
    .W1_2_0_o(grp_updateHidden_fu_493_W1_2_0_o),
    .W1_2_0_o_ap_vld(grp_updateHidden_fu_493_W1_2_0_o_ap_vld),
    .W1_3_0_i(W1_3_0),
    .W1_3_0_o(grp_updateHidden_fu_493_W1_3_0_o),
    .W1_3_0_o_ap_vld(grp_updateHidden_fu_493_W1_3_0_o_ap_vld),
    .W1_4_0_i(W1_4_0),
    .W1_4_0_o(grp_updateHidden_fu_493_W1_4_0_o),
    .W1_4_0_o_ap_vld(grp_updateHidden_fu_493_W1_4_0_o_ap_vld),
    .W1_5_0_i(W1_5_0),
    .W1_5_0_o(grp_updateHidden_fu_493_W1_5_0_o),
    .W1_5_0_o_ap_vld(grp_updateHidden_fu_493_W1_5_0_o_ap_vld),
    .W1_6_0_i(W1_6_0),
    .W1_6_0_o(grp_updateHidden_fu_493_W1_6_0_o),
    .W1_6_0_o_ap_vld(grp_updateHidden_fu_493_W1_6_0_o_ap_vld),
    .W1_7_0_i(W1_7_0),
    .W1_7_0_o(grp_updateHidden_fu_493_W1_7_0_o),
    .W1_7_0_o_ap_vld(grp_updateHidden_fu_493_W1_7_0_o_ap_vld),
    .W1_0_1_i(W1_0_1),
    .W1_0_1_o(grp_updateHidden_fu_493_W1_0_1_o),
    .W1_0_1_o_ap_vld(grp_updateHidden_fu_493_W1_0_1_o_ap_vld),
    .W1_1_1_i(W1_1_1),
    .W1_1_1_o(grp_updateHidden_fu_493_W1_1_1_o),
    .W1_1_1_o_ap_vld(grp_updateHidden_fu_493_W1_1_1_o_ap_vld),
    .W1_2_1_i(W1_2_1),
    .W1_2_1_o(grp_updateHidden_fu_493_W1_2_1_o),
    .W1_2_1_o_ap_vld(grp_updateHidden_fu_493_W1_2_1_o_ap_vld),
    .W1_3_1_i(W1_3_1),
    .W1_3_1_o(grp_updateHidden_fu_493_W1_3_1_o),
    .W1_3_1_o_ap_vld(grp_updateHidden_fu_493_W1_3_1_o_ap_vld),
    .W1_4_1_i(W1_4_1),
    .W1_4_1_o(grp_updateHidden_fu_493_W1_4_1_o),
    .W1_4_1_o_ap_vld(grp_updateHidden_fu_493_W1_4_1_o_ap_vld),
    .W1_5_1_i(W1_5_1),
    .W1_5_1_o(grp_updateHidden_fu_493_W1_5_1_o),
    .W1_5_1_o_ap_vld(grp_updateHidden_fu_493_W1_5_1_o_ap_vld),
    .W1_6_1_i(W1_6_1),
    .W1_6_1_o(grp_updateHidden_fu_493_W1_6_1_o),
    .W1_6_1_o_ap_vld(grp_updateHidden_fu_493_W1_6_1_o_ap_vld),
    .W1_7_1_i(W1_7_1),
    .W1_7_1_o(grp_updateHidden_fu_493_W1_7_1_o),
    .W1_7_1_o_ap_vld(grp_updateHidden_fu_493_W1_7_1_o_ap_vld),
    .W1_0_2_i(W1_0_2),
    .W1_0_2_o(grp_updateHidden_fu_493_W1_0_2_o),
    .W1_0_2_o_ap_vld(grp_updateHidden_fu_493_W1_0_2_o_ap_vld),
    .W1_1_2_i(W1_1_2),
    .W1_1_2_o(grp_updateHidden_fu_493_W1_1_2_o),
    .W1_1_2_o_ap_vld(grp_updateHidden_fu_493_W1_1_2_o_ap_vld),
    .W1_2_2_i(W1_2_2),
    .W1_2_2_o(grp_updateHidden_fu_493_W1_2_2_o),
    .W1_2_2_o_ap_vld(grp_updateHidden_fu_493_W1_2_2_o_ap_vld),
    .W1_3_2_i(W1_3_2),
    .W1_3_2_o(grp_updateHidden_fu_493_W1_3_2_o),
    .W1_3_2_o_ap_vld(grp_updateHidden_fu_493_W1_3_2_o_ap_vld),
    .W1_4_2_i(W1_4_2),
    .W1_4_2_o(grp_updateHidden_fu_493_W1_4_2_o),
    .W1_4_2_o_ap_vld(grp_updateHidden_fu_493_W1_4_2_o_ap_vld),
    .W1_5_2_i(W1_5_2),
    .W1_5_2_o(grp_updateHidden_fu_493_W1_5_2_o),
    .W1_5_2_o_ap_vld(grp_updateHidden_fu_493_W1_5_2_o_ap_vld),
    .W1_6_2_i(W1_6_2),
    .W1_6_2_o(grp_updateHidden_fu_493_W1_6_2_o),
    .W1_6_2_o_ap_vld(grp_updateHidden_fu_493_W1_6_2_o_ap_vld),
    .W1_7_2_i(W1_7_2),
    .W1_7_2_o(grp_updateHidden_fu_493_W1_7_2_o),
    .W1_7_2_o_ap_vld(grp_updateHidden_fu_493_W1_7_2_o_ap_vld),
    .W1_0_3_i(W1_0_3),
    .W1_0_3_o(grp_updateHidden_fu_493_W1_0_3_o),
    .W1_0_3_o_ap_vld(grp_updateHidden_fu_493_W1_0_3_o_ap_vld),
    .W1_1_3_i(W1_1_3),
    .W1_1_3_o(grp_updateHidden_fu_493_W1_1_3_o),
    .W1_1_3_o_ap_vld(grp_updateHidden_fu_493_W1_1_3_o_ap_vld),
    .W1_2_3_i(W1_2_3),
    .W1_2_3_o(grp_updateHidden_fu_493_W1_2_3_o),
    .W1_2_3_o_ap_vld(grp_updateHidden_fu_493_W1_2_3_o_ap_vld),
    .W1_3_3_i(W1_3_3),
    .W1_3_3_o(grp_updateHidden_fu_493_W1_3_3_o),
    .W1_3_3_o_ap_vld(grp_updateHidden_fu_493_W1_3_3_o_ap_vld),
    .W1_4_3_i(W1_4_3),
    .W1_4_3_o(grp_updateHidden_fu_493_W1_4_3_o),
    .W1_4_3_o_ap_vld(grp_updateHidden_fu_493_W1_4_3_o_ap_vld),
    .W1_5_3_i(W1_5_3),
    .W1_5_3_o(grp_updateHidden_fu_493_W1_5_3_o),
    .W1_5_3_o_ap_vld(grp_updateHidden_fu_493_W1_5_3_o_ap_vld),
    .W1_6_3_i(W1_6_3),
    .W1_6_3_o(grp_updateHidden_fu_493_W1_6_3_o),
    .W1_6_3_o_ap_vld(grp_updateHidden_fu_493_W1_6_3_o_ap_vld),
    .W1_7_3_i(W1_7_3),
    .W1_7_3_o(grp_updateHidden_fu_493_W1_7_3_o),
    .W1_7_3_o_ap_vld(grp_updateHidden_fu_493_W1_7_3_o_ap_vld)
);

train_step_train_step_Pipeline_VITIS_LOOP_136_1 grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_start),
    .ap_done(grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_done),
    .ap_idle(grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_idle),
    .ap_ready(grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_ready),
    .W1_out_address0(grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_address0),
    .W1_out_ce0(grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_ce0),
    .W1_out_we0(grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_we0),
    .W1_out_d0(grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_d0),
    .W1_out_address1(grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_address1),
    .W1_out_ce1(grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_ce1),
    .W1_out_we1(grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_we1),
    .W1_out_d1(grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_d1),
    .W1_0_0_load(W1_0_0),
    .W1_0_1_load(W1_0_1),
    .W1_0_2_load(W1_0_2),
    .W1_0_3_load(W1_0_3),
    .W1_1_0_load(W1_1_0),
    .W1_1_1_load(W1_1_1),
    .W1_1_2_load(W1_1_2),
    .W1_1_3_load(W1_1_3),
    .W1_2_0_load(W1_2_0),
    .W1_2_1_load(W1_2_1),
    .W1_2_2_load(W1_2_2),
    .W1_2_3_load(W1_2_3),
    .W1_3_0_load(W1_3_0),
    .W1_3_1_load(W1_3_1),
    .W1_3_2_load(W1_3_2),
    .W1_3_3_load(W1_3_3),
    .W1_4_0_load(W1_4_0),
    .W1_4_1_load(W1_4_1),
    .W1_4_2_load(W1_4_2),
    .W1_4_3_load(W1_4_3),
    .W1_5_0_load(W1_5_0),
    .W1_5_1_load(W1_5_1),
    .W1_5_2_load(W1_5_2),
    .W1_5_3_load(W1_5_3),
    .W1_6_0_load(W1_6_0),
    .W1_6_1_load(W1_6_1),
    .W1_6_2_load(W1_6_2),
    .W1_6_3_load(W1_6_3),
    .W1_7_0_load(W1_7_0),
    .W1_7_1_load(W1_7_1),
    .W1_7_2_load(W1_7_2),
    .W1_7_3_load(W1_7_3)
);

train_step_train_step_Pipeline_VITIS_LOOP_141_4 grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_start),
    .ap_done(grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_done),
    .ap_idle(grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_idle),
    .ap_ready(grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_ready),
    .W2_out_address0(grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_W2_out_address0),
    .W2_out_ce0(grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_W2_out_ce0),
    .W2_out_we0(grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_W2_out_we0),
    .W2_out_d0(grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_W2_out_d0)
);

train_step_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .img_pos_0(img_pos_0),
    .img_pos_1(img_pos_1),
    .img_pos_2(img_pos_2),
    .img_pos_3(img_pos_3),
    .img_pos_4(img_pos_4),
    .img_pos_5(img_pos_5),
    .img_pos_6(img_pos_6),
    .img_pos_7(img_pos_7),
    .img_neg_0(img_neg_0),
    .img_neg_1(img_neg_1),
    .img_neg_2(img_neg_2),
    .img_neg_3(img_neg_3),
    .img_neg_4(img_neg_4),
    .img_neg_5(img_neg_5),
    .img_neg_6(img_neg_6),
    .img_neg_7(img_neg_7),
    .last_sample(last_sample),
    .sample_idx(sample_idx),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

train_step_mul_32ns_34ns_42_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 42 ))
mul_32ns_34ns_42_2_1_U199(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_629_p0),
    .din1(grp_fu_629_p1),
    .ce(1'b1),
    .dout(grp_fu_629_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_start_reg <= 1'b1;
        end else if ((grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_ready == 1'b1)) begin
            grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_start_reg <= 1'b1;
        end else if ((grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_ready == 1'b1)) begin
            grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_updateHidden_fu_493_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state7) & (1'b1 == ap_CS_fsm_state6))) begin
            grp_updateHidden_fu_493_ap_start_reg <= 1'b1;
        end else if ((grp_updateHidden_fu_493_ap_ready == 1'b1)) begin
            grp_updateHidden_fu_493_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_0_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_0_0 <= grp_updateHidden_fu_493_W1_0_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_0_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_0_1 <= grp_updateHidden_fu_493_W1_0_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_0_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_0_2 <= grp_updateHidden_fu_493_W1_0_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_0_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_0_3 <= grp_updateHidden_fu_493_W1_0_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_1_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_1_0 <= grp_updateHidden_fu_493_W1_1_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_1_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_1_1 <= grp_updateHidden_fu_493_W1_1_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_1_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_1_2 <= grp_updateHidden_fu_493_W1_1_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_1_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_1_3 <= grp_updateHidden_fu_493_W1_1_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_2_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_2_0 <= grp_updateHidden_fu_493_W1_2_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_2_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_2_1 <= grp_updateHidden_fu_493_W1_2_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_2_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_2_2 <= grp_updateHidden_fu_493_W1_2_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_2_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_2_3 <= grp_updateHidden_fu_493_W1_2_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_3_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_3_0 <= grp_updateHidden_fu_493_W1_3_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_3_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_3_1 <= grp_updateHidden_fu_493_W1_3_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_3_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_3_2 <= grp_updateHidden_fu_493_W1_3_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_3_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_3_3 <= grp_updateHidden_fu_493_W1_3_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_4_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_4_0 <= grp_updateHidden_fu_493_W1_4_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_4_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_4_1 <= grp_updateHidden_fu_493_W1_4_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_4_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_4_2 <= grp_updateHidden_fu_493_W1_4_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_4_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_4_3 <= grp_updateHidden_fu_493_W1_4_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_5_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_5_0 <= grp_updateHidden_fu_493_W1_5_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_5_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_5_1 <= grp_updateHidden_fu_493_W1_5_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_5_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_5_2 <= grp_updateHidden_fu_493_W1_5_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_5_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_5_3 <= grp_updateHidden_fu_493_W1_5_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_6_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_6_0 <= grp_updateHidden_fu_493_W1_6_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_6_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_6_1 <= grp_updateHidden_fu_493_W1_6_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_6_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_6_2 <= grp_updateHidden_fu_493_W1_6_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_6_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_6_3 <= grp_updateHidden_fu_493_W1_6_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_7_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_7_0 <= grp_updateHidden_fu_493_W1_7_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_7_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_7_1 <= grp_updateHidden_fu_493_W1_7_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_7_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_7_2 <= grp_updateHidden_fu_493_W1_7_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_updateHidden_fu_493_W1_7_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        W1_7_3 <= grp_updateHidden_fu_493_W1_7_3_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln146_reg_1011 <= icmp_ln146_fu_646_p2;
        img_pos_0_read_reg_918 <= img_pos_0;
        img_pos_1_read_reg_924 <= img_pos_1;
        img_pos_2_read_reg_930 <= img_pos_2;
        img_pos_3_read_reg_936 <= img_pos_3;
        img_pos_4_read_reg_942 <= img_pos_4;
        img_pos_5_read_reg_948 <= img_pos_5;
        img_pos_6_read_reg_954 <= img_pos_6;
        img_pos_7_read_reg_960 <= img_pos_7;
        sub_ln145_reg_1006 <= sub_ln145_fu_640_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        train_mulmulmulstep_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed <= grp_forwardHidden_fu_325_ap_return_3;
        train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_1 <= grp_forwardHidden_fu_325_ap_return_2;
        train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_2 <= grp_forwardHidden_fu_325_ap_return_1;
        train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_3 <= grp_forwardHidden_fu_325_ap_return_0;
        train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_4 <= grp_forwardHidden_fu_409_ap_return_3;
        train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_5 <= grp_forwardHidden_fu_409_ap_return_2;
        train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_6 <= grp_forwardHidden_fu_409_ap_return_1;
        train_step_ap_fixed_const_ap_fixed_const_int_int_ap_uint_volatile_ap_fixed_7 <= grp_forwardHidden_fu_409_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        trunc_ln1_reg_1021 <= {{grp_fu_629_p2[41:38]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state12_on_subcall_done)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        leds_port_ap_vld = 1'b1;
    end else begin
        leds_port_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign W1_out_address0 = grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_address0;

assign W1_out_address1 = grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_address1;

assign W1_out_ce0 = grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_ce0;

assign W1_out_ce1 = grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_ce1;

assign W1_out_d0 = grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_d0;

assign W1_out_d1 = grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_d1;

assign W1_out_we0 = grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_we0;

assign W1_out_we1 = grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_W1_out_we1;

assign W2_out_address0 = grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_W2_out_address0;

assign W2_out_ce0 = grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_W2_out_ce0;

assign W2_out_d0 = grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_W2_out_d0;

assign W2_out_we0 = grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_W2_out_we0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state7 = ap_NS_fsm[32'd6];

always @ (*) begin
    ap_block_state12_on_subcall_done = ((grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_done == 1'b0) | (grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_done == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fu_629_p0 = grp_fu_629_p00;

assign grp_fu_629_p00 = sub_ln145_reg_1006;

assign grp_fu_629_p1 = 42'd5609753203;

assign grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_start = grp_train_step_Pipeline_VITIS_LOOP_136_1_fu_585_ap_start_reg;

assign grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_start = grp_train_step_Pipeline_VITIS_LOOP_141_4_fu_623_ap_start_reg;

assign grp_updateHidden_fu_493_ap_start = grp_updateHidden_fu_493_ap_start_reg;

assign icmp_ln146_fu_646_p2 = ((last_sample != 32'd0) ? 1'b1 : 1'b0);

assign leds_port = ((icmp_ln146_reg_1011[0:0] == 1'b1) ? xor_ln146_fu_666_p2 : trunc_ln1_reg_1021);

assign shl_ln145_fu_634_p2 = sample_idx << 32'd4;

assign sub_ln145_fu_640_p2 = (shl_ln145_fu_634_p2 - sample_idx);

assign xor_ln146_fu_666_p2 = (trunc_ln1_reg_1021 ^ 4'd15);

endmodule //train_step
