// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module train_step_forwardHidden (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_val,
        input_1_val,
        input_2_val,
        input_3_val,
        input_4_val,
        input_5_val,
        input_6_val,
        input_7_val,
        input_8_val,
        input_9_val,
        input_10_val,
        input_11_val,
        input_12_val,
        input_13_val,
        input_14_val,
        input_15_val,
        input_16_val,
        input_17_val,
        input_18_val,
        input_19_val,
        input_20_val,
        input_21_val,
        input_22_val,
        input_23_val,
        input_24_val,
        input_25_val,
        input_26_val,
        input_27_val,
        input_28_val,
        input_29_val,
        input_30_val,
        input_31_val,
        input_32_val,
        input_33_val,
        input_34_val,
        input_35_val,
        input_36_val,
        input_37_val,
        input_38_val,
        input_39_val,
        input_40_val,
        input_41_val,
        input_42_val,
        input_43_val,
        input_44_val,
        input_45_val,
        input_46_val,
        input_47_val,
        input_48_val,
        input_49_val,
        input_50_val,
        input_51_val,
        input_52_val,
        input_53_val,
        input_54_val,
        input_55_val,
        input_56_val,
        input_57_val,
        input_58_val,
        input_59_val,
        input_60_val,
        input_61_val,
        input_62_val,
        input_63_val,
        hidden_0,
        hidden_0_ap_vld,
        hidden_1,
        hidden_1_ap_vld,
        hidden_2,
        hidden_2_ap_vld,
        hidden_3,
        hidden_3_ap_vld,
        hidden_4,
        hidden_4_ap_vld,
        hidden_5,
        hidden_5_ap_vld,
        hidden_6,
        hidden_6_ap_vld,
        hidden_7,
        hidden_7_ap_vld,
        hidden_8,
        hidden_8_ap_vld,
        hidden_9,
        hidden_9_ap_vld,
        hidden_10,
        hidden_10_ap_vld,
        hidden_11,
        hidden_11_ap_vld,
        hidden_12,
        hidden_12_ap_vld,
        hidden_13,
        hidden_13_ap_vld,
        hidden_14,
        hidden_14_ap_vld,
        hidden_15,
        hidden_15_ap_vld,
        hidden_16,
        hidden_16_ap_vld,
        hidden_17,
        hidden_17_ap_vld,
        hidden_18,
        hidden_18_ap_vld,
        hidden_19,
        hidden_19_ap_vld,
        hidden_20,
        hidden_20_ap_vld,
        hidden_21,
        hidden_21_ap_vld,
        hidden_22,
        hidden_22_ap_vld,
        hidden_23,
        hidden_23_ap_vld,
        hidden_24,
        hidden_24_ap_vld,
        hidden_25,
        hidden_25_ap_vld,
        hidden_26,
        hidden_26_ap_vld,
        hidden_27,
        hidden_27_ap_vld,
        hidden_28,
        hidden_28_ap_vld,
        hidden_29,
        hidden_29_ap_vld,
        hidden_30,
        hidden_30_ap_vld,
        hidden_31,
        hidden_31_ap_vld,
        m_axi_WEIGHTS_0_AWVALID,
        m_axi_WEIGHTS_0_AWREADY,
        m_axi_WEIGHTS_0_AWADDR,
        m_axi_WEIGHTS_0_AWID,
        m_axi_WEIGHTS_0_AWLEN,
        m_axi_WEIGHTS_0_AWSIZE,
        m_axi_WEIGHTS_0_AWBURST,
        m_axi_WEIGHTS_0_AWLOCK,
        m_axi_WEIGHTS_0_AWCACHE,
        m_axi_WEIGHTS_0_AWPROT,
        m_axi_WEIGHTS_0_AWQOS,
        m_axi_WEIGHTS_0_AWREGION,
        m_axi_WEIGHTS_0_AWUSER,
        m_axi_WEIGHTS_0_WVALID,
        m_axi_WEIGHTS_0_WREADY,
        m_axi_WEIGHTS_0_WDATA,
        m_axi_WEIGHTS_0_WSTRB,
        m_axi_WEIGHTS_0_WLAST,
        m_axi_WEIGHTS_0_WID,
        m_axi_WEIGHTS_0_WUSER,
        m_axi_WEIGHTS_0_ARVALID,
        m_axi_WEIGHTS_0_ARREADY,
        m_axi_WEIGHTS_0_ARADDR,
        m_axi_WEIGHTS_0_ARID,
        m_axi_WEIGHTS_0_ARLEN,
        m_axi_WEIGHTS_0_ARSIZE,
        m_axi_WEIGHTS_0_ARBURST,
        m_axi_WEIGHTS_0_ARLOCK,
        m_axi_WEIGHTS_0_ARCACHE,
        m_axi_WEIGHTS_0_ARPROT,
        m_axi_WEIGHTS_0_ARQOS,
        m_axi_WEIGHTS_0_ARREGION,
        m_axi_WEIGHTS_0_ARUSER,
        m_axi_WEIGHTS_0_RVALID,
        m_axi_WEIGHTS_0_RREADY,
        m_axi_WEIGHTS_0_RDATA,
        m_axi_WEIGHTS_0_RLAST,
        m_axi_WEIGHTS_0_RID,
        m_axi_WEIGHTS_0_RFIFONUM,
        m_axi_WEIGHTS_0_RUSER,
        m_axi_WEIGHTS_0_RRESP,
        m_axi_WEIGHTS_0_BVALID,
        m_axi_WEIGHTS_0_BREADY,
        m_axi_WEIGHTS_0_BRESP,
        m_axi_WEIGHTS_0_BID,
        m_axi_WEIGHTS_0_BUSER,
        W1
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [1:0] input_0_val;
input  [1:0] input_1_val;
input  [1:0] input_2_val;
input  [1:0] input_3_val;
input  [1:0] input_4_val;
input  [1:0] input_5_val;
input  [1:0] input_6_val;
input  [1:0] input_7_val;
input  [1:0] input_8_val;
input  [1:0] input_9_val;
input  [1:0] input_10_val;
input  [1:0] input_11_val;
input  [1:0] input_12_val;
input  [1:0] input_13_val;
input  [1:0] input_14_val;
input  [1:0] input_15_val;
input  [1:0] input_16_val;
input  [1:0] input_17_val;
input  [1:0] input_18_val;
input  [1:0] input_19_val;
input  [1:0] input_20_val;
input  [1:0] input_21_val;
input  [1:0] input_22_val;
input  [1:0] input_23_val;
input  [1:0] input_24_val;
input  [1:0] input_25_val;
input  [1:0] input_26_val;
input  [1:0] input_27_val;
input  [1:0] input_28_val;
input  [1:0] input_29_val;
input  [1:0] input_30_val;
input  [1:0] input_31_val;
input  [1:0] input_32_val;
input  [1:0] input_33_val;
input  [1:0] input_34_val;
input  [1:0] input_35_val;
input  [1:0] input_36_val;
input  [1:0] input_37_val;
input  [1:0] input_38_val;
input  [1:0] input_39_val;
input  [1:0] input_40_val;
input  [1:0] input_41_val;
input  [1:0] input_42_val;
input  [1:0] input_43_val;
input  [1:0] input_44_val;
input  [1:0] input_45_val;
input  [1:0] input_46_val;
input  [1:0] input_47_val;
input  [1:0] input_48_val;
input  [1:0] input_49_val;
input  [1:0] input_50_val;
input  [1:0] input_51_val;
input  [1:0] input_52_val;
input  [1:0] input_53_val;
input  [1:0] input_54_val;
input  [1:0] input_55_val;
input  [1:0] input_56_val;
input  [1:0] input_57_val;
input  [1:0] input_58_val;
input  [1:0] input_59_val;
input  [1:0] input_60_val;
input  [1:0] input_61_val;
input  [1:0] input_62_val;
input  [1:0] input_63_val;
output  [1:0] hidden_0;
output   hidden_0_ap_vld;
output  [1:0] hidden_1;
output   hidden_1_ap_vld;
output  [1:0] hidden_2;
output   hidden_2_ap_vld;
output  [1:0] hidden_3;
output   hidden_3_ap_vld;
output  [1:0] hidden_4;
output   hidden_4_ap_vld;
output  [1:0] hidden_5;
output   hidden_5_ap_vld;
output  [1:0] hidden_6;
output   hidden_6_ap_vld;
output  [1:0] hidden_7;
output   hidden_7_ap_vld;
output  [1:0] hidden_8;
output   hidden_8_ap_vld;
output  [1:0] hidden_9;
output   hidden_9_ap_vld;
output  [1:0] hidden_10;
output   hidden_10_ap_vld;
output  [1:0] hidden_11;
output   hidden_11_ap_vld;
output  [1:0] hidden_12;
output   hidden_12_ap_vld;
output  [1:0] hidden_13;
output   hidden_13_ap_vld;
output  [1:0] hidden_14;
output   hidden_14_ap_vld;
output  [1:0] hidden_15;
output   hidden_15_ap_vld;
output  [1:0] hidden_16;
output   hidden_16_ap_vld;
output  [1:0] hidden_17;
output   hidden_17_ap_vld;
output  [1:0] hidden_18;
output   hidden_18_ap_vld;
output  [1:0] hidden_19;
output   hidden_19_ap_vld;
output  [1:0] hidden_20;
output   hidden_20_ap_vld;
output  [1:0] hidden_21;
output   hidden_21_ap_vld;
output  [1:0] hidden_22;
output   hidden_22_ap_vld;
output  [1:0] hidden_23;
output   hidden_23_ap_vld;
output  [1:0] hidden_24;
output   hidden_24_ap_vld;
output  [1:0] hidden_25;
output   hidden_25_ap_vld;
output  [1:0] hidden_26;
output   hidden_26_ap_vld;
output  [1:0] hidden_27;
output   hidden_27_ap_vld;
output  [1:0] hidden_28;
output   hidden_28_ap_vld;
output  [1:0] hidden_29;
output   hidden_29_ap_vld;
output  [1:0] hidden_30;
output   hidden_30_ap_vld;
output  [1:0] hidden_31;
output   hidden_31_ap_vld;
output   m_axi_WEIGHTS_0_AWVALID;
input   m_axi_WEIGHTS_0_AWREADY;
output  [63:0] m_axi_WEIGHTS_0_AWADDR;
output  [0:0] m_axi_WEIGHTS_0_AWID;
output  [31:0] m_axi_WEIGHTS_0_AWLEN;
output  [2:0] m_axi_WEIGHTS_0_AWSIZE;
output  [1:0] m_axi_WEIGHTS_0_AWBURST;
output  [1:0] m_axi_WEIGHTS_0_AWLOCK;
output  [3:0] m_axi_WEIGHTS_0_AWCACHE;
output  [2:0] m_axi_WEIGHTS_0_AWPROT;
output  [3:0] m_axi_WEIGHTS_0_AWQOS;
output  [3:0] m_axi_WEIGHTS_0_AWREGION;
output  [0:0] m_axi_WEIGHTS_0_AWUSER;
output   m_axi_WEIGHTS_0_WVALID;
input   m_axi_WEIGHTS_0_WREADY;
output  [7:0] m_axi_WEIGHTS_0_WDATA;
output  [0:0] m_axi_WEIGHTS_0_WSTRB;
output   m_axi_WEIGHTS_0_WLAST;
output  [0:0] m_axi_WEIGHTS_0_WID;
output  [0:0] m_axi_WEIGHTS_0_WUSER;
output   m_axi_WEIGHTS_0_ARVALID;
input   m_axi_WEIGHTS_0_ARREADY;
output  [63:0] m_axi_WEIGHTS_0_ARADDR;
output  [0:0] m_axi_WEIGHTS_0_ARID;
output  [31:0] m_axi_WEIGHTS_0_ARLEN;
output  [2:0] m_axi_WEIGHTS_0_ARSIZE;
output  [1:0] m_axi_WEIGHTS_0_ARBURST;
output  [1:0] m_axi_WEIGHTS_0_ARLOCK;
output  [3:0] m_axi_WEIGHTS_0_ARCACHE;
output  [2:0] m_axi_WEIGHTS_0_ARPROT;
output  [3:0] m_axi_WEIGHTS_0_ARQOS;
output  [3:0] m_axi_WEIGHTS_0_ARREGION;
output  [0:0] m_axi_WEIGHTS_0_ARUSER;
input   m_axi_WEIGHTS_0_RVALID;
output   m_axi_WEIGHTS_0_RREADY;
input  [7:0] m_axi_WEIGHTS_0_RDATA;
input   m_axi_WEIGHTS_0_RLAST;
input  [0:0] m_axi_WEIGHTS_0_RID;
input  [10:0] m_axi_WEIGHTS_0_RFIFONUM;
input  [0:0] m_axi_WEIGHTS_0_RUSER;
input  [1:0] m_axi_WEIGHTS_0_RRESP;
input   m_axi_WEIGHTS_0_BVALID;
output   m_axi_WEIGHTS_0_BREADY;
input  [1:0] m_axi_WEIGHTS_0_BRESP;
input  [0:0] m_axi_WEIGHTS_0_BID;
input  [0:0] m_axi_WEIGHTS_0_BUSER;
input  [63:0] W1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[1:0] hidden_0;
reg[1:0] hidden_1;
reg[1:0] hidden_2;
reg[1:0] hidden_3;
reg[1:0] hidden_4;
reg[1:0] hidden_5;
reg[1:0] hidden_6;
reg[1:0] hidden_7;
reg[1:0] hidden_8;
reg[1:0] hidden_9;
reg[1:0] hidden_10;
reg[1:0] hidden_11;
reg[1:0] hidden_12;
reg[1:0] hidden_13;
reg[1:0] hidden_14;
reg[1:0] hidden_15;
reg[1:0] hidden_16;
reg[1:0] hidden_17;
reg[1:0] hidden_18;
reg[1:0] hidden_19;
reg[1:0] hidden_20;
reg[1:0] hidden_21;
reg[1:0] hidden_22;
reg[1:0] hidden_23;
reg[1:0] hidden_24;
reg[1:0] hidden_25;
reg[1:0] hidden_26;
reg[1:0] hidden_27;
reg[1:0] hidden_28;
reg[1:0] hidden_29;
reg[1:0] hidden_30;
reg[1:0] hidden_31;
reg m_axi_WEIGHTS_0_ARVALID;
reg[63:0] m_axi_WEIGHTS_0_ARADDR;
reg[0:0] m_axi_WEIGHTS_0_ARID;
reg[31:0] m_axi_WEIGHTS_0_ARLEN;
reg[2:0] m_axi_WEIGHTS_0_ARSIZE;
reg[1:0] m_axi_WEIGHTS_0_ARBURST;
reg[1:0] m_axi_WEIGHTS_0_ARLOCK;
reg[3:0] m_axi_WEIGHTS_0_ARCACHE;
reg[2:0] m_axi_WEIGHTS_0_ARPROT;
reg[3:0] m_axi_WEIGHTS_0_ARQOS;
reg[3:0] m_axi_WEIGHTS_0_ARREGION;
reg[0:0] m_axi_WEIGHTS_0_ARUSER;
reg m_axi_WEIGHTS_0_RREADY;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    WEIGHTS_blk_n_AR;
wire    ap_CS_fsm_state9;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_idle;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_ready;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWVALID;
wire   [63:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWADDR;
wire   [0:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWID;
wire   [31:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWLEN;
wire   [2:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWSIZE;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWBURST;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWLOCK;
wire   [3:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWCACHE;
wire   [2:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWPROT;
wire   [3:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWQOS;
wire   [3:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWREGION;
wire   [0:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWUSER;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WVALID;
wire   [7:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WDATA;
wire   [0:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WSTRB;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WLAST;
wire   [0:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WID;
wire   [0:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WUSER;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARVALID;
wire   [63:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARADDR;
wire   [0:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARID;
wire   [31:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARLEN;
wire   [2:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARSIZE;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARBURST;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARLOCK;
wire   [3:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARCACHE;
wire   [2:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARPROT;
wire   [3:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARQOS;
wire   [3:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARREGION;
wire   [0:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARUSER;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_RREADY;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_BREADY;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2_ap_vld;
wire   [1:0] grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1;
wire    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1_ap_vld;
reg    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start_reg;
reg   [1:0] hidden_0_reg;
wire    ap_CS_fsm_state10;
reg   [1:0] hidden_31_reg;
reg   [1:0] hidden_30_reg;
reg   [1:0] hidden_29_reg;
reg   [1:0] hidden_28_reg;
reg   [1:0] hidden_27_reg;
reg   [1:0] hidden_26_reg;
reg   [1:0] hidden_25_reg;
reg   [1:0] hidden_24_reg;
reg   [1:0] hidden_23_reg;
reg   [1:0] hidden_22_reg;
reg   [1:0] hidden_21_reg;
reg   [1:0] hidden_20_reg;
reg   [1:0] hidden_19_reg;
reg   [1:0] hidden_18_reg;
reg   [1:0] hidden_17_reg;
reg   [1:0] hidden_16_reg;
reg   [1:0] hidden_15_reg;
reg   [1:0] hidden_14_reg;
reg   [1:0] hidden_13_reg;
reg   [1:0] hidden_12_reg;
reg   [1:0] hidden_11_reg;
reg   [1:0] hidden_10_reg;
reg   [1:0] hidden_9_reg;
reg   [1:0] hidden_8_reg;
reg   [1:0] hidden_7_reg;
reg   [1:0] hidden_6_reg;
reg   [1:0] hidden_5_reg;
reg   [1:0] hidden_4_reg;
reg   [1:0] hidden_3_reg;
reg   [1:0] hidden_2_reg;
reg   [1:0] hidden_1_reg;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start_reg = 1'b0;
end

train_step_forwardHidden_Pipeline_VITIS_LOOP_36_1 grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start),
    .ap_done(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done),
    .ap_idle(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_idle),
    .ap_ready(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_ready),
    .m_axi_WEIGHTS_0_AWVALID(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWVALID),
    .m_axi_WEIGHTS_0_AWREADY(1'b0),
    .m_axi_WEIGHTS_0_AWADDR(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWADDR),
    .m_axi_WEIGHTS_0_AWID(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWID),
    .m_axi_WEIGHTS_0_AWLEN(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWLEN),
    .m_axi_WEIGHTS_0_AWSIZE(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWSIZE),
    .m_axi_WEIGHTS_0_AWBURST(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWBURST),
    .m_axi_WEIGHTS_0_AWLOCK(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWLOCK),
    .m_axi_WEIGHTS_0_AWCACHE(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWCACHE),
    .m_axi_WEIGHTS_0_AWPROT(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWPROT),
    .m_axi_WEIGHTS_0_AWQOS(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWQOS),
    .m_axi_WEIGHTS_0_AWREGION(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWREGION),
    .m_axi_WEIGHTS_0_AWUSER(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWUSER),
    .m_axi_WEIGHTS_0_WVALID(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WVALID),
    .m_axi_WEIGHTS_0_WREADY(1'b0),
    .m_axi_WEIGHTS_0_WDATA(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WDATA),
    .m_axi_WEIGHTS_0_WSTRB(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WSTRB),
    .m_axi_WEIGHTS_0_WLAST(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WLAST),
    .m_axi_WEIGHTS_0_WID(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WID),
    .m_axi_WEIGHTS_0_WUSER(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WUSER),
    .m_axi_WEIGHTS_0_ARVALID(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARVALID),
    .m_axi_WEIGHTS_0_ARREADY(m_axi_WEIGHTS_0_ARREADY),
    .m_axi_WEIGHTS_0_ARADDR(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARADDR),
    .m_axi_WEIGHTS_0_ARID(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARID),
    .m_axi_WEIGHTS_0_ARLEN(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARLEN),
    .m_axi_WEIGHTS_0_ARSIZE(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARSIZE),
    .m_axi_WEIGHTS_0_ARBURST(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARBURST),
    .m_axi_WEIGHTS_0_ARLOCK(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARLOCK),
    .m_axi_WEIGHTS_0_ARCACHE(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARCACHE),
    .m_axi_WEIGHTS_0_ARPROT(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARPROT),
    .m_axi_WEIGHTS_0_ARQOS(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARQOS),
    .m_axi_WEIGHTS_0_ARREGION(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARREGION),
    .m_axi_WEIGHTS_0_ARUSER(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARUSER),
    .m_axi_WEIGHTS_0_RVALID(m_axi_WEIGHTS_0_RVALID),
    .m_axi_WEIGHTS_0_RREADY(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_RREADY),
    .m_axi_WEIGHTS_0_RDATA(m_axi_WEIGHTS_0_RDATA),
    .m_axi_WEIGHTS_0_RLAST(m_axi_WEIGHTS_0_RLAST),
    .m_axi_WEIGHTS_0_RID(m_axi_WEIGHTS_0_RID),
    .m_axi_WEIGHTS_0_RFIFONUM(m_axi_WEIGHTS_0_RFIFONUM),
    .m_axi_WEIGHTS_0_RUSER(m_axi_WEIGHTS_0_RUSER),
    .m_axi_WEIGHTS_0_RRESP(m_axi_WEIGHTS_0_RRESP),
    .m_axi_WEIGHTS_0_BVALID(1'b0),
    .m_axi_WEIGHTS_0_BREADY(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_BREADY),
    .m_axi_WEIGHTS_0_BRESP(2'd0),
    .m_axi_WEIGHTS_0_BID(1'd0),
    .m_axi_WEIGHTS_0_BUSER(1'd0),
    .hidden_0(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0),
    .hidden_0_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0_ap_vld),
    .W1(W1),
    .hidden_31(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31),
    .hidden_31_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31_ap_vld),
    .hidden_30(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30),
    .hidden_30_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30_ap_vld),
    .hidden_29(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29),
    .hidden_29_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29_ap_vld),
    .hidden_28(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28),
    .hidden_28_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28_ap_vld),
    .hidden_27(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27),
    .hidden_27_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27_ap_vld),
    .hidden_26(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26),
    .hidden_26_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26_ap_vld),
    .hidden_25(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25),
    .hidden_25_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25_ap_vld),
    .hidden_24(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24),
    .hidden_24_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24_ap_vld),
    .hidden_23(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23),
    .hidden_23_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23_ap_vld),
    .hidden_22(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22),
    .hidden_22_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22_ap_vld),
    .hidden_21(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21),
    .hidden_21_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21_ap_vld),
    .hidden_20(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20),
    .hidden_20_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20_ap_vld),
    .hidden_19(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19),
    .hidden_19_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19_ap_vld),
    .hidden_18(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18),
    .hidden_18_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18_ap_vld),
    .hidden_17(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17),
    .hidden_17_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17_ap_vld),
    .hidden_16(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16),
    .hidden_16_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16_ap_vld),
    .hidden_15(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15),
    .hidden_15_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15_ap_vld),
    .hidden_14(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14),
    .hidden_14_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14_ap_vld),
    .hidden_13(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13),
    .hidden_13_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13_ap_vld),
    .hidden_12(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12),
    .hidden_12_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12_ap_vld),
    .hidden_11(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11),
    .hidden_11_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11_ap_vld),
    .hidden_10(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10),
    .hidden_10_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10_ap_vld),
    .hidden_9(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9),
    .hidden_9_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9_ap_vld),
    .hidden_8(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8),
    .hidden_8_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8_ap_vld),
    .hidden_7(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7),
    .hidden_7_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7_ap_vld),
    .hidden_6(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6),
    .hidden_6_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6_ap_vld),
    .hidden_5(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5),
    .hidden_5_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5_ap_vld),
    .hidden_4(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4),
    .hidden_4_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4_ap_vld),
    .hidden_3(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3),
    .hidden_3_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3_ap_vld),
    .hidden_2(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2),
    .hidden_2_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2_ap_vld),
    .hidden_1(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1),
    .hidden_1_ap_vld(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1_ap_vld),
    .sext_ln41(input_0_val),
    .sext_ln41_1(input_1_val),
    .sext_ln41_2(input_2_val),
    .sext_ln41_3(input_3_val),
    .sext_ln41_4(input_4_val),
    .sext_ln41_5(input_5_val),
    .sext_ln41_6(input_6_val),
    .sext_ln41_7(input_7_val),
    .sext_ln41_8(input_8_val),
    .sext_ln41_9(input_9_val),
    .sext_ln41_10(input_10_val),
    .sext_ln41_11(input_11_val),
    .sext_ln41_12(input_12_val),
    .sext_ln41_13(input_13_val),
    .sext_ln41_14(input_14_val),
    .sext_ln41_15(input_15_val),
    .sext_ln41_16(input_16_val),
    .sext_ln41_17(input_17_val),
    .sext_ln41_18(input_18_val),
    .sext_ln41_19(input_19_val),
    .sext_ln41_20(input_20_val),
    .sext_ln41_21(input_21_val),
    .sext_ln41_22(input_22_val),
    .sext_ln41_23(input_23_val),
    .sext_ln41_24(input_24_val),
    .sext_ln41_25(input_25_val),
    .sext_ln41_26(input_26_val),
    .sext_ln41_27(input_27_val),
    .sext_ln41_28(input_28_val),
    .sext_ln41_29(input_29_val),
    .sext_ln41_30(input_30_val),
    .sext_ln41_31(input_31_val),
    .sext_ln41_32(input_32_val),
    .sext_ln41_33(input_33_val),
    .sext_ln41_34(input_34_val),
    .sext_ln41_35(input_35_val),
    .sext_ln41_36(input_36_val),
    .sext_ln41_37(input_37_val),
    .sext_ln41_38(input_38_val),
    .sext_ln41_39(input_39_val),
    .sext_ln41_40(input_40_val),
    .sext_ln41_41(input_41_val),
    .sext_ln41_42(input_42_val),
    .sext_ln41_43(input_43_val),
    .sext_ln41_44(input_44_val),
    .sext_ln41_45(input_45_val),
    .sext_ln41_46(input_46_val),
    .sext_ln41_47(input_47_val),
    .sext_ln41_48(input_48_val),
    .sext_ln41_49(input_49_val),
    .sext_ln41_50(input_50_val),
    .sext_ln41_51(input_51_val),
    .sext_ln41_52(input_52_val),
    .sext_ln41_53(input_53_val),
    .sext_ln41_54(input_54_val),
    .sext_ln41_55(input_55_val),
    .sext_ln41_56(input_56_val),
    .sext_ln41_57(input_57_val),
    .sext_ln41_58(input_58_val),
    .sext_ln41_59(input_59_val),
    .sext_ln41_60(input_60_val),
    .sext_ln41_61(input_61_val),
    .sext_ln41_62(input_62_val),
    .sext_ln36(input_63_val)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start_reg <= 1'b1;
        end else if ((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_ready == 1'b1)) begin
            grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_0_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_10_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_11_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_12_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_13_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_14_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_15_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_16_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_17_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_18_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_19_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_1_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_20_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_21_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_22_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_23_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_24_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_25_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_26_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_27_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_28_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_29_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_2_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_30_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_31_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_3_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_4_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_5_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_6_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_7_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_8_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_9_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        WEIGHTS_blk_n_AR = m_axi_WEIGHTS_0_ARREADY;
    end else begin
        WEIGHTS_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_WEIGHTS_0_ARREADY == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_0 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0;
    end else begin
        hidden_0 = hidden_0_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_1 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1;
    end else begin
        hidden_1 = hidden_1_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_10 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10;
    end else begin
        hidden_10 = hidden_10_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_11 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11;
    end else begin
        hidden_11 = hidden_11_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_12 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12;
    end else begin
        hidden_12 = hidden_12_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_13 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13;
    end else begin
        hidden_13 = hidden_13_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_14 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14;
    end else begin
        hidden_14 = hidden_14_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_15 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15;
    end else begin
        hidden_15 = hidden_15_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_16 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16;
    end else begin
        hidden_16 = hidden_16_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_17 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17;
    end else begin
        hidden_17 = hidden_17_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_18 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18;
    end else begin
        hidden_18 = hidden_18_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_19 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19;
    end else begin
        hidden_19 = hidden_19_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_2 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2;
    end else begin
        hidden_2 = hidden_2_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_20 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20;
    end else begin
        hidden_20 = hidden_20_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_21 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21;
    end else begin
        hidden_21 = hidden_21_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_22 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22;
    end else begin
        hidden_22 = hidden_22_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_23 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23;
    end else begin
        hidden_23 = hidden_23_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_24 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24;
    end else begin
        hidden_24 = hidden_24_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_25 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25;
    end else begin
        hidden_25 = hidden_25_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_26 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26;
    end else begin
        hidden_26 = hidden_26_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_27 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27;
    end else begin
        hidden_27 = hidden_27_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_28 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28;
    end else begin
        hidden_28 = hidden_28_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_29 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29;
    end else begin
        hidden_29 = hidden_29_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_3 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3;
    end else begin
        hidden_3 = hidden_3_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_30 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30;
    end else begin
        hidden_30 = hidden_30_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_31 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31;
    end else begin
        hidden_31 = hidden_31_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_4 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4;
    end else begin
        hidden_4 = hidden_4_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_5 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5;
    end else begin
        hidden_5 = hidden_5_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_6 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6;
    end else begin
        hidden_6 = hidden_6_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_7 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7;
    end else begin
        hidden_7 = hidden_7_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_8 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8;
    end else begin
        hidden_8 = hidden_8_reg;
    end
end

always @ (*) begin
    if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        hidden_9 = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9;
    end else begin
        hidden_9 = hidden_9_reg;
    end
end

always @ (*) begin
    if ((~((m_axi_WEIGHTS_0_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_WEIGHTS_0_ARADDR = W1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARADDR = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARADDR;
    end else begin
        m_axi_WEIGHTS_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARBURST = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARBURST;
    end else begin
        m_axi_WEIGHTS_0_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARCACHE = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARCACHE;
    end else begin
        m_axi_WEIGHTS_0_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARID = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARID;
    end else begin
        m_axi_WEIGHTS_0_ARID = 1'd0;
    end
end

always @ (*) begin
    if ((~((m_axi_WEIGHTS_0_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_WEIGHTS_0_ARLEN = 64'd2048;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARLEN = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARLEN;
    end else begin
        m_axi_WEIGHTS_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARLOCK = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARLOCK;
    end else begin
        m_axi_WEIGHTS_0_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARPROT = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARPROT;
    end else begin
        m_axi_WEIGHTS_0_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARQOS = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARQOS;
    end else begin
        m_axi_WEIGHTS_0_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARREGION = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARREGION;
    end else begin
        m_axi_WEIGHTS_0_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARSIZE = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARSIZE;
    end else begin
        m_axi_WEIGHTS_0_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARUSER = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARUSER;
    end else begin
        m_axi_WEIGHTS_0_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if ((~((m_axi_WEIGHTS_0_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_WEIGHTS_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARVALID = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARVALID;
    end else begin
        m_axi_WEIGHTS_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_RREADY = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_RREADY;
    end else begin
        m_axi_WEIGHTS_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((m_axi_WEIGHTS_0_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start_reg;

assign hidden_0_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0_ap_vld;

assign hidden_10_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10_ap_vld;

assign hidden_11_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11_ap_vld;

assign hidden_12_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12_ap_vld;

assign hidden_13_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13_ap_vld;

assign hidden_14_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14_ap_vld;

assign hidden_15_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15_ap_vld;

assign hidden_16_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16_ap_vld;

assign hidden_17_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17_ap_vld;

assign hidden_18_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18_ap_vld;

assign hidden_19_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19_ap_vld;

assign hidden_1_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1_ap_vld;

assign hidden_20_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20_ap_vld;

assign hidden_21_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21_ap_vld;

assign hidden_22_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22_ap_vld;

assign hidden_23_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23_ap_vld;

assign hidden_24_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24_ap_vld;

assign hidden_25_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25_ap_vld;

assign hidden_26_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26_ap_vld;

assign hidden_27_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27_ap_vld;

assign hidden_28_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28_ap_vld;

assign hidden_29_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29_ap_vld;

assign hidden_2_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2_ap_vld;

assign hidden_30_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30_ap_vld;

assign hidden_31_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31_ap_vld;

assign hidden_3_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3_ap_vld;

assign hidden_4_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4_ap_vld;

assign hidden_5_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5_ap_vld;

assign hidden_6_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6_ap_vld;

assign hidden_7_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7_ap_vld;

assign hidden_8_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8_ap_vld;

assign hidden_9_ap_vld = grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9_ap_vld;

assign m_axi_WEIGHTS_0_AWADDR = 64'd0;

assign m_axi_WEIGHTS_0_AWBURST = 2'd0;

assign m_axi_WEIGHTS_0_AWCACHE = 4'd0;

assign m_axi_WEIGHTS_0_AWID = 1'd0;

assign m_axi_WEIGHTS_0_AWLEN = 32'd0;

assign m_axi_WEIGHTS_0_AWLOCK = 2'd0;

assign m_axi_WEIGHTS_0_AWPROT = 3'd0;

assign m_axi_WEIGHTS_0_AWQOS = 4'd0;

assign m_axi_WEIGHTS_0_AWREGION = 4'd0;

assign m_axi_WEIGHTS_0_AWSIZE = 3'd0;

assign m_axi_WEIGHTS_0_AWUSER = 1'd0;

assign m_axi_WEIGHTS_0_AWVALID = 1'b0;

assign m_axi_WEIGHTS_0_BREADY = 1'b0;

assign m_axi_WEIGHTS_0_WDATA = 8'd0;

assign m_axi_WEIGHTS_0_WID = 1'd0;

assign m_axi_WEIGHTS_0_WLAST = 1'b0;

assign m_axi_WEIGHTS_0_WSTRB = 1'd0;

assign m_axi_WEIGHTS_0_WUSER = 1'd0;

assign m_axi_WEIGHTS_0_WVALID = 1'b0;

endmodule //train_step_forwardHidden
