// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module train_step_forwardOutput (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hidden_0_val,
        hidden_1_val,
        hidden_2_val,
        hidden_3_val,
        hidden_4_val,
        hidden_5_val,
        hidden_6_val,
        hidden_7_val,
        hidden_8_val,
        hidden_9_val,
        hidden_10_val,
        hidden_11_val,
        hidden_12_val,
        hidden_13_val,
        hidden_14_val,
        hidden_15_val,
        hidden_16_val,
        hidden_17_val,
        hidden_18_val,
        hidden_19_val,
        hidden_20_val,
        hidden_21_val,
        hidden_22_val,
        hidden_23_val,
        hidden_24_val,
        hidden_25_val,
        hidden_26_val,
        hidden_27_val,
        hidden_28_val,
        hidden_29_val,
        hidden_30_val,
        hidden_31_val,
        output_0,
        output_0_ap_vld,
        output_1,
        output_1_ap_vld,
        output_2,
        output_2_ap_vld,
        output_3,
        output_3_ap_vld,
        output_4,
        output_4_ap_vld,
        output_5,
        output_5_ap_vld,
        output_6,
        output_6_ap_vld,
        output_7,
        output_7_ap_vld,
        output_8,
        output_8_ap_vld,
        output_9,
        output_9_ap_vld,
        m_axi_WEIGHTS_0_AWVALID,
        m_axi_WEIGHTS_0_AWREADY,
        m_axi_WEIGHTS_0_AWADDR,
        m_axi_WEIGHTS_0_AWID,
        m_axi_WEIGHTS_0_AWLEN,
        m_axi_WEIGHTS_0_AWSIZE,
        m_axi_WEIGHTS_0_AWBURST,
        m_axi_WEIGHTS_0_AWLOCK,
        m_axi_WEIGHTS_0_AWCACHE,
        m_axi_WEIGHTS_0_AWPROT,
        m_axi_WEIGHTS_0_AWQOS,
        m_axi_WEIGHTS_0_AWREGION,
        m_axi_WEIGHTS_0_AWUSER,
        m_axi_WEIGHTS_0_WVALID,
        m_axi_WEIGHTS_0_WREADY,
        m_axi_WEIGHTS_0_WDATA,
        m_axi_WEIGHTS_0_WSTRB,
        m_axi_WEIGHTS_0_WLAST,
        m_axi_WEIGHTS_0_WID,
        m_axi_WEIGHTS_0_WUSER,
        m_axi_WEIGHTS_0_ARVALID,
        m_axi_WEIGHTS_0_ARREADY,
        m_axi_WEIGHTS_0_ARADDR,
        m_axi_WEIGHTS_0_ARID,
        m_axi_WEIGHTS_0_ARLEN,
        m_axi_WEIGHTS_0_ARSIZE,
        m_axi_WEIGHTS_0_ARBURST,
        m_axi_WEIGHTS_0_ARLOCK,
        m_axi_WEIGHTS_0_ARCACHE,
        m_axi_WEIGHTS_0_ARPROT,
        m_axi_WEIGHTS_0_ARQOS,
        m_axi_WEIGHTS_0_ARREGION,
        m_axi_WEIGHTS_0_ARUSER,
        m_axi_WEIGHTS_0_RVALID,
        m_axi_WEIGHTS_0_RREADY,
        m_axi_WEIGHTS_0_RDATA,
        m_axi_WEIGHTS_0_RLAST,
        m_axi_WEIGHTS_0_RID,
        m_axi_WEIGHTS_0_RFIFONUM,
        m_axi_WEIGHTS_0_RUSER,
        m_axi_WEIGHTS_0_RRESP,
        m_axi_WEIGHTS_0_BVALID,
        m_axi_WEIGHTS_0_BREADY,
        m_axi_WEIGHTS_0_BRESP,
        m_axi_WEIGHTS_0_BID,
        m_axi_WEIGHTS_0_BUSER,
        W2
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [1:0] hidden_0_val;
input  [1:0] hidden_1_val;
input  [1:0] hidden_2_val;
input  [1:0] hidden_3_val;
input  [1:0] hidden_4_val;
input  [1:0] hidden_5_val;
input  [1:0] hidden_6_val;
input  [1:0] hidden_7_val;
input  [1:0] hidden_8_val;
input  [1:0] hidden_9_val;
input  [1:0] hidden_10_val;
input  [1:0] hidden_11_val;
input  [1:0] hidden_12_val;
input  [1:0] hidden_13_val;
input  [1:0] hidden_14_val;
input  [1:0] hidden_15_val;
input  [1:0] hidden_16_val;
input  [1:0] hidden_17_val;
input  [1:0] hidden_18_val;
input  [1:0] hidden_19_val;
input  [1:0] hidden_20_val;
input  [1:0] hidden_21_val;
input  [1:0] hidden_22_val;
input  [1:0] hidden_23_val;
input  [1:0] hidden_24_val;
input  [1:0] hidden_25_val;
input  [1:0] hidden_26_val;
input  [1:0] hidden_27_val;
input  [1:0] hidden_28_val;
input  [1:0] hidden_29_val;
input  [1:0] hidden_30_val;
input  [1:0] hidden_31_val;
output  [1:0] output_0;
output   output_0_ap_vld;
output  [1:0] output_1;
output   output_1_ap_vld;
output  [1:0] output_2;
output   output_2_ap_vld;
output  [1:0] output_3;
output   output_3_ap_vld;
output  [1:0] output_4;
output   output_4_ap_vld;
output  [1:0] output_5;
output   output_5_ap_vld;
output  [1:0] output_6;
output   output_6_ap_vld;
output  [1:0] output_7;
output   output_7_ap_vld;
output  [1:0] output_8;
output   output_8_ap_vld;
output  [1:0] output_9;
output   output_9_ap_vld;
output   m_axi_WEIGHTS_0_AWVALID;
input   m_axi_WEIGHTS_0_AWREADY;
output  [63:0] m_axi_WEIGHTS_0_AWADDR;
output  [0:0] m_axi_WEIGHTS_0_AWID;
output  [31:0] m_axi_WEIGHTS_0_AWLEN;
output  [2:0] m_axi_WEIGHTS_0_AWSIZE;
output  [1:0] m_axi_WEIGHTS_0_AWBURST;
output  [1:0] m_axi_WEIGHTS_0_AWLOCK;
output  [3:0] m_axi_WEIGHTS_0_AWCACHE;
output  [2:0] m_axi_WEIGHTS_0_AWPROT;
output  [3:0] m_axi_WEIGHTS_0_AWQOS;
output  [3:0] m_axi_WEIGHTS_0_AWREGION;
output  [0:0] m_axi_WEIGHTS_0_AWUSER;
output   m_axi_WEIGHTS_0_WVALID;
input   m_axi_WEIGHTS_0_WREADY;
output  [7:0] m_axi_WEIGHTS_0_WDATA;
output  [0:0] m_axi_WEIGHTS_0_WSTRB;
output   m_axi_WEIGHTS_0_WLAST;
output  [0:0] m_axi_WEIGHTS_0_WID;
output  [0:0] m_axi_WEIGHTS_0_WUSER;
output   m_axi_WEIGHTS_0_ARVALID;
input   m_axi_WEIGHTS_0_ARREADY;
output  [63:0] m_axi_WEIGHTS_0_ARADDR;
output  [0:0] m_axi_WEIGHTS_0_ARID;
output  [31:0] m_axi_WEIGHTS_0_ARLEN;
output  [2:0] m_axi_WEIGHTS_0_ARSIZE;
output  [1:0] m_axi_WEIGHTS_0_ARBURST;
output  [1:0] m_axi_WEIGHTS_0_ARLOCK;
output  [3:0] m_axi_WEIGHTS_0_ARCACHE;
output  [2:0] m_axi_WEIGHTS_0_ARPROT;
output  [3:0] m_axi_WEIGHTS_0_ARQOS;
output  [3:0] m_axi_WEIGHTS_0_ARREGION;
output  [0:0] m_axi_WEIGHTS_0_ARUSER;
input   m_axi_WEIGHTS_0_RVALID;
output   m_axi_WEIGHTS_0_RREADY;
input  [7:0] m_axi_WEIGHTS_0_RDATA;
input   m_axi_WEIGHTS_0_RLAST;
input  [0:0] m_axi_WEIGHTS_0_RID;
input  [10:0] m_axi_WEIGHTS_0_RFIFONUM;
input  [0:0] m_axi_WEIGHTS_0_RUSER;
input  [1:0] m_axi_WEIGHTS_0_RRESP;
input   m_axi_WEIGHTS_0_BVALID;
output   m_axi_WEIGHTS_0_BREADY;
input  [1:0] m_axi_WEIGHTS_0_BRESP;
input  [0:0] m_axi_WEIGHTS_0_BID;
input  [0:0] m_axi_WEIGHTS_0_BUSER;
input  [63:0] W2;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[1:0] output_0;
reg[1:0] output_1;
reg[1:0] output_2;
reg[1:0] output_3;
reg[1:0] output_4;
reg[1:0] output_5;
reg[1:0] output_6;
reg[1:0] output_7;
reg[1:0] output_8;
reg[1:0] output_9;
reg m_axi_WEIGHTS_0_ARVALID;
reg[63:0] m_axi_WEIGHTS_0_ARADDR;
reg[0:0] m_axi_WEIGHTS_0_ARID;
reg[31:0] m_axi_WEIGHTS_0_ARLEN;
reg[2:0] m_axi_WEIGHTS_0_ARSIZE;
reg[1:0] m_axi_WEIGHTS_0_ARBURST;
reg[1:0] m_axi_WEIGHTS_0_ARLOCK;
reg[3:0] m_axi_WEIGHTS_0_ARCACHE;
reg[2:0] m_axi_WEIGHTS_0_ARPROT;
reg[3:0] m_axi_WEIGHTS_0_ARQOS;
reg[3:0] m_axi_WEIGHTS_0_ARREGION;
reg[0:0] m_axi_WEIGHTS_0_ARUSER;
reg m_axi_WEIGHTS_0_RREADY;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    WEIGHTS_blk_n_AR;
wire    ap_CS_fsm_state9;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_start;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_done;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_idle;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_ready;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWVALID;
wire   [63:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWADDR;
wire   [0:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWID;
wire   [31:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWLEN;
wire   [2:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWSIZE;
wire   [1:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWBURST;
wire   [1:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWLOCK;
wire   [3:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWCACHE;
wire   [2:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWPROT;
wire   [3:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWQOS;
wire   [3:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWREGION;
wire   [0:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWUSER;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_WVALID;
wire   [7:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_WDATA;
wire   [0:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_WSTRB;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_WLAST;
wire   [0:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_WID;
wire   [0:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_WUSER;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARVALID;
wire   [63:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARADDR;
wire   [0:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARID;
wire   [31:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARLEN;
wire   [2:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARSIZE;
wire   [1:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARBURST;
wire   [1:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARLOCK;
wire   [3:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARCACHE;
wire   [2:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARPROT;
wire   [3:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARQOS;
wire   [3:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARREGION;
wire   [0:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARUSER;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_RREADY;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_BREADY;
wire   [1:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_0;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_0_ap_vld;
wire   [1:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_9;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_9_ap_vld;
wire   [1:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_8;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_8_ap_vld;
wire   [1:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_7;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_7_ap_vld;
wire   [1:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_6;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_6_ap_vld;
wire   [1:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_5;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_5_ap_vld;
wire   [1:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_4;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_4_ap_vld;
wire   [1:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_3;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_3_ap_vld;
wire   [1:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_2;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_2_ap_vld;
wire   [1:0] grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_1;
wire    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_1_ap_vld;
reg    grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_start_reg;
reg   [1:0] output_0_reg;
wire    ap_CS_fsm_state10;
reg   [1:0] output_9_reg;
reg   [1:0] output_8_reg;
reg   [1:0] output_7_reg;
reg   [1:0] output_6_reg;
reg   [1:0] output_5_reg;
reg   [1:0] output_4_reg;
reg   [1:0] output_3_reg;
reg   [1:0] output_2_reg;
reg   [1:0] output_1_reg;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_start_reg = 1'b0;
end

train_step_forwardOutput_Pipeline_VITIS_LOOP_54_1 grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_start),
    .ap_done(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_done),
    .ap_idle(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_idle),
    .ap_ready(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_ready),
    .m_axi_WEIGHTS_0_AWVALID(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWVALID),
    .m_axi_WEIGHTS_0_AWREADY(1'b0),
    .m_axi_WEIGHTS_0_AWADDR(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWADDR),
    .m_axi_WEIGHTS_0_AWID(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWID),
    .m_axi_WEIGHTS_0_AWLEN(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWLEN),
    .m_axi_WEIGHTS_0_AWSIZE(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWSIZE),
    .m_axi_WEIGHTS_0_AWBURST(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWBURST),
    .m_axi_WEIGHTS_0_AWLOCK(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWLOCK),
    .m_axi_WEIGHTS_0_AWCACHE(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWCACHE),
    .m_axi_WEIGHTS_0_AWPROT(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWPROT),
    .m_axi_WEIGHTS_0_AWQOS(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWQOS),
    .m_axi_WEIGHTS_0_AWREGION(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWREGION),
    .m_axi_WEIGHTS_0_AWUSER(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_AWUSER),
    .m_axi_WEIGHTS_0_WVALID(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_WVALID),
    .m_axi_WEIGHTS_0_WREADY(1'b0),
    .m_axi_WEIGHTS_0_WDATA(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_WDATA),
    .m_axi_WEIGHTS_0_WSTRB(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_WSTRB),
    .m_axi_WEIGHTS_0_WLAST(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_WLAST),
    .m_axi_WEIGHTS_0_WID(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_WID),
    .m_axi_WEIGHTS_0_WUSER(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_WUSER),
    .m_axi_WEIGHTS_0_ARVALID(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARVALID),
    .m_axi_WEIGHTS_0_ARREADY(m_axi_WEIGHTS_0_ARREADY),
    .m_axi_WEIGHTS_0_ARADDR(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARADDR),
    .m_axi_WEIGHTS_0_ARID(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARID),
    .m_axi_WEIGHTS_0_ARLEN(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARLEN),
    .m_axi_WEIGHTS_0_ARSIZE(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARSIZE),
    .m_axi_WEIGHTS_0_ARBURST(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARBURST),
    .m_axi_WEIGHTS_0_ARLOCK(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARLOCK),
    .m_axi_WEIGHTS_0_ARCACHE(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARCACHE),
    .m_axi_WEIGHTS_0_ARPROT(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARPROT),
    .m_axi_WEIGHTS_0_ARQOS(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARQOS),
    .m_axi_WEIGHTS_0_ARREGION(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARREGION),
    .m_axi_WEIGHTS_0_ARUSER(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARUSER),
    .m_axi_WEIGHTS_0_RVALID(m_axi_WEIGHTS_0_RVALID),
    .m_axi_WEIGHTS_0_RREADY(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_RREADY),
    .m_axi_WEIGHTS_0_RDATA(m_axi_WEIGHTS_0_RDATA),
    .m_axi_WEIGHTS_0_RLAST(m_axi_WEIGHTS_0_RLAST),
    .m_axi_WEIGHTS_0_RID(m_axi_WEIGHTS_0_RID),
    .m_axi_WEIGHTS_0_RFIFONUM(m_axi_WEIGHTS_0_RFIFONUM),
    .m_axi_WEIGHTS_0_RUSER(m_axi_WEIGHTS_0_RUSER),
    .m_axi_WEIGHTS_0_RRESP(m_axi_WEIGHTS_0_RRESP),
    .m_axi_WEIGHTS_0_BVALID(1'b0),
    .m_axi_WEIGHTS_0_BREADY(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_BREADY),
    .m_axi_WEIGHTS_0_BRESP(2'd0),
    .m_axi_WEIGHTS_0_BID(1'd0),
    .m_axi_WEIGHTS_0_BUSER(1'd0),
    .output_0(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_0),
    .output_0_ap_vld(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_0_ap_vld),
    .W2(W2),
    .output_9(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_9),
    .output_9_ap_vld(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_9_ap_vld),
    .output_8(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_8),
    .output_8_ap_vld(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_8_ap_vld),
    .output_7(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_7),
    .output_7_ap_vld(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_7_ap_vld),
    .output_6(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_6),
    .output_6_ap_vld(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_6_ap_vld),
    .output_5(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_5),
    .output_5_ap_vld(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_5_ap_vld),
    .output_4(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_4),
    .output_4_ap_vld(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_4_ap_vld),
    .output_3(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_3),
    .output_3_ap_vld(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_3_ap_vld),
    .output_2(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_2),
    .output_2_ap_vld(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_2_ap_vld),
    .output_1(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_1),
    .output_1_ap_vld(grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_1_ap_vld),
    .sext_ln58(hidden_0_val),
    .sext_ln58_1(hidden_1_val),
    .sext_ln58_2(hidden_2_val),
    .sext_ln58_3(hidden_3_val),
    .sext_ln58_4(hidden_4_val),
    .sext_ln58_5(hidden_5_val),
    .sext_ln58_6(hidden_6_val),
    .sext_ln58_7(hidden_7_val),
    .sext_ln58_8(hidden_8_val),
    .sext_ln58_9(hidden_9_val),
    .sext_ln58_10(hidden_10_val),
    .sext_ln58_11(hidden_11_val),
    .sext_ln58_12(hidden_12_val),
    .sext_ln58_13(hidden_13_val),
    .sext_ln58_14(hidden_14_val),
    .sext_ln58_15(hidden_15_val),
    .sext_ln58_16(hidden_16_val),
    .sext_ln58_17(hidden_17_val),
    .sext_ln58_18(hidden_18_val),
    .sext_ln58_19(hidden_19_val),
    .sext_ln58_20(hidden_20_val),
    .sext_ln58_21(hidden_21_val),
    .sext_ln58_22(hidden_22_val),
    .sext_ln58_23(hidden_23_val),
    .sext_ln58_24(hidden_24_val),
    .sext_ln58_25(hidden_25_val),
    .sext_ln58_26(hidden_26_val),
    .sext_ln58_27(hidden_27_val),
    .sext_ln58_28(hidden_28_val),
    .sext_ln58_29(hidden_29_val),
    .sext_ln58_30(hidden_30_val),
    .sext_ln54(hidden_31_val)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_start_reg <= 1'b1;
        end else if ((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_ready == 1'b1)) begin
            grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_0_reg <= grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_1_reg <= grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_2_reg <= grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_3_reg <= grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_4_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_4_reg <= grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_4;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_5_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_5_reg <= grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_5;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_6_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_6_reg <= grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_6;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_7_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_7_reg <= grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_7;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_8_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_8_reg <= grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_8;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_9_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_9_reg <= grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_9;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        WEIGHTS_blk_n_AR = m_axi_WEIGHTS_0_ARREADY;
    end else begin
        WEIGHTS_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (m_axi_WEIGHTS_0_ARREADY == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (m_axi_WEIGHTS_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_WEIGHTS_0_ARADDR = W2;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARADDR = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARADDR;
    end else begin
        m_axi_WEIGHTS_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARBURST = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARBURST;
    end else begin
        m_axi_WEIGHTS_0_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARCACHE = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARCACHE;
    end else begin
        m_axi_WEIGHTS_0_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARID = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARID;
    end else begin
        m_axi_WEIGHTS_0_ARID = 1'd0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (m_axi_WEIGHTS_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_WEIGHTS_0_ARLEN = 64'd320;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARLEN = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARLEN;
    end else begin
        m_axi_WEIGHTS_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARLOCK = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARLOCK;
    end else begin
        m_axi_WEIGHTS_0_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARPROT = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARPROT;
    end else begin
        m_axi_WEIGHTS_0_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARQOS = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARQOS;
    end else begin
        m_axi_WEIGHTS_0_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARREGION = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARREGION;
    end else begin
        m_axi_WEIGHTS_0_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARSIZE = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARSIZE;
    end else begin
        m_axi_WEIGHTS_0_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARUSER = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARUSER;
    end else begin
        m_axi_WEIGHTS_0_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (m_axi_WEIGHTS_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_WEIGHTS_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_ARVALID = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_ARVALID;
    end else begin
        m_axi_WEIGHTS_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_WEIGHTS_0_RREADY = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_m_axi_WEIGHTS_0_RREADY;
    end else begin
        m_axi_WEIGHTS_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_0 = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_0;
    end else begin
        output_0 = output_0_reg;
    end
end

always @ (*) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_1 = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_1;
    end else begin
        output_1 = output_1_reg;
    end
end

always @ (*) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_2 = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_2;
    end else begin
        output_2 = output_2_reg;
    end
end

always @ (*) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_3 = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_3;
    end else begin
        output_3 = output_3_reg;
    end
end

always @ (*) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_4_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_4 = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_4;
    end else begin
        output_4 = output_4_reg;
    end
end

always @ (*) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_5_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_5 = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_5;
    end else begin
        output_5 = output_5_reg;
    end
end

always @ (*) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_6_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_6 = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_6;
    end else begin
        output_6 = output_6_reg;
    end
end

always @ (*) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_7_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_7 = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_7;
    end else begin
        output_7 = output_7_reg;
    end
end

always @ (*) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_8_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_8 = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_8;
    end else begin
        output_8 = output_8_reg;
    end
end

always @ (*) begin
    if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_9_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        output_9 = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_9;
    end else begin
        output_9 = output_9_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (m_axi_WEIGHTS_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_start = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_ap_start_reg;

assign m_axi_WEIGHTS_0_AWADDR = 64'd0;

assign m_axi_WEIGHTS_0_AWBURST = 2'd0;

assign m_axi_WEIGHTS_0_AWCACHE = 4'd0;

assign m_axi_WEIGHTS_0_AWID = 1'd0;

assign m_axi_WEIGHTS_0_AWLEN = 32'd0;

assign m_axi_WEIGHTS_0_AWLOCK = 2'd0;

assign m_axi_WEIGHTS_0_AWPROT = 3'd0;

assign m_axi_WEIGHTS_0_AWQOS = 4'd0;

assign m_axi_WEIGHTS_0_AWREGION = 4'd0;

assign m_axi_WEIGHTS_0_AWSIZE = 3'd0;

assign m_axi_WEIGHTS_0_AWUSER = 1'd0;

assign m_axi_WEIGHTS_0_AWVALID = 1'b0;

assign m_axi_WEIGHTS_0_BREADY = 1'b0;

assign m_axi_WEIGHTS_0_WDATA = 8'd0;

assign m_axi_WEIGHTS_0_WID = 1'd0;

assign m_axi_WEIGHTS_0_WLAST = 1'b0;

assign m_axi_WEIGHTS_0_WSTRB = 1'd0;

assign m_axi_WEIGHTS_0_WUSER = 1'd0;

assign m_axi_WEIGHTS_0_WVALID = 1'b0;

assign output_0_ap_vld = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_0_ap_vld;

assign output_1_ap_vld = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_1_ap_vld;

assign output_2_ap_vld = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_2_ap_vld;

assign output_3_ap_vld = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_3_ap_vld;

assign output_4_ap_vld = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_4_ap_vld;

assign output_5_ap_vld = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_5_ap_vld;

assign output_6_ap_vld = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_6_ap_vld;

assign output_7_ap_vld = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_7_ap_vld;

assign output_8_ap_vld = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_8_ap_vld;

assign output_9_ap_vld = grp_forwardOutput_Pipeline_VITIS_LOOP_54_1_fu_321_output_9_ap_vld;

endmodule //train_step_forwardOutput
