-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity train_step_forwardHidden is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_0_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_1_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_2_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_3_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_4_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_5_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_6_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_7_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_8_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_9_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_10_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_11_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_12_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_13_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_14_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_15_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_16_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_17_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_18_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_19_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_20_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_21_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_22_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_23_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_24_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_25_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_26_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_27_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_28_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_29_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_30_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_31_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_32_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_33_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_34_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_35_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_36_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_37_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_38_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_39_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_40_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_41_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_42_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_43_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_44_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_45_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_46_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_47_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_48_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_49_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_50_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_51_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_52_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_53_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_54_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_55_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_56_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_57_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_58_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_59_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_60_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_61_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_62_val : IN STD_LOGIC_VECTOR (1 downto 0);
    input_63_val : IN STD_LOGIC_VECTOR (1 downto 0);
    hidden_0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_0_ap_vld : OUT STD_LOGIC;
    hidden_1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_1_ap_vld : OUT STD_LOGIC;
    hidden_2 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_2_ap_vld : OUT STD_LOGIC;
    hidden_3 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_3_ap_vld : OUT STD_LOGIC;
    hidden_4 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_4_ap_vld : OUT STD_LOGIC;
    hidden_5 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_5_ap_vld : OUT STD_LOGIC;
    hidden_6 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_6_ap_vld : OUT STD_LOGIC;
    hidden_7 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_7_ap_vld : OUT STD_LOGIC;
    hidden_8 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_8_ap_vld : OUT STD_LOGIC;
    hidden_9 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_9_ap_vld : OUT STD_LOGIC;
    hidden_10 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_10_ap_vld : OUT STD_LOGIC;
    hidden_11 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_11_ap_vld : OUT STD_LOGIC;
    hidden_12 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_12_ap_vld : OUT STD_LOGIC;
    hidden_13 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_13_ap_vld : OUT STD_LOGIC;
    hidden_14 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_14_ap_vld : OUT STD_LOGIC;
    hidden_15 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_15_ap_vld : OUT STD_LOGIC;
    hidden_16 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_16_ap_vld : OUT STD_LOGIC;
    hidden_17 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_17_ap_vld : OUT STD_LOGIC;
    hidden_18 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_18_ap_vld : OUT STD_LOGIC;
    hidden_19 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_19_ap_vld : OUT STD_LOGIC;
    hidden_20 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_20_ap_vld : OUT STD_LOGIC;
    hidden_21 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_21_ap_vld : OUT STD_LOGIC;
    hidden_22 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_22_ap_vld : OUT STD_LOGIC;
    hidden_23 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_23_ap_vld : OUT STD_LOGIC;
    hidden_24 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_24_ap_vld : OUT STD_LOGIC;
    hidden_25 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_25_ap_vld : OUT STD_LOGIC;
    hidden_26 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_26_ap_vld : OUT STD_LOGIC;
    hidden_27 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_27_ap_vld : OUT STD_LOGIC;
    hidden_28 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_28_ap_vld : OUT STD_LOGIC;
    hidden_29 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_29_ap_vld : OUT STD_LOGIC;
    hidden_30 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_30_ap_vld : OUT STD_LOGIC;
    hidden_31 : OUT STD_LOGIC_VECTOR (1 downto 0);
    hidden_31_ap_vld : OUT STD_LOGIC;
    m_axi_WEIGHTS_0_AWVALID : OUT STD_LOGIC;
    m_axi_WEIGHTS_0_AWREADY : IN STD_LOGIC;
    m_axi_WEIGHTS_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_WEIGHTS_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_WEIGHTS_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WEIGHTS_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WEIGHTS_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WEIGHTS_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WEIGHTS_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WEIGHTS_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WEIGHTS_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WEIGHTS_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_0_WVALID : OUT STD_LOGIC;
    m_axi_WEIGHTS_0_WREADY : IN STD_LOGIC;
    m_axi_WEIGHTS_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_WEIGHTS_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_0_WLAST : OUT STD_LOGIC;
    m_axi_WEIGHTS_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_0_ARVALID : OUT STD_LOGIC;
    m_axi_WEIGHTS_0_ARREADY : IN STD_LOGIC;
    m_axi_WEIGHTS_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_WEIGHTS_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_WEIGHTS_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WEIGHTS_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WEIGHTS_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WEIGHTS_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WEIGHTS_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WEIGHTS_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WEIGHTS_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WEIGHTS_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_0_RVALID : IN STD_LOGIC;
    m_axi_WEIGHTS_0_RREADY : OUT STD_LOGIC;
    m_axi_WEIGHTS_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_WEIGHTS_0_RLAST : IN STD_LOGIC;
    m_axi_WEIGHTS_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_WEIGHTS_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WEIGHTS_0_BVALID : IN STD_LOGIC;
    m_axi_WEIGHTS_0_BREADY : OUT STD_LOGIC;
    m_axi_WEIGHTS_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WEIGHTS_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    W1 : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of train_step_forwardHidden is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv64_800 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000100000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal WEIGHTS_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_idle : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_ready : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWVALID : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WVALID : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WLAST : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARVALID : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_RREADY : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_BREADY : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1_ap_vld : STD_LOGIC;
    signal grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start_reg : STD_LOGIC := '0';
    signal hidden_0_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal hidden_31_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_30_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_29_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_28_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_27_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_26_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_25_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_24_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_23_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_22_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_21_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_20_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_19_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_18_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_17_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_16_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_15_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_14_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_13_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component train_step_forwardHidden_Pipeline_VITIS_LOOP_36_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_WEIGHTS_0_AWVALID : OUT STD_LOGIC;
        m_axi_WEIGHTS_0_AWREADY : IN STD_LOGIC;
        m_axi_WEIGHTS_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_WEIGHTS_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WEIGHTS_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_WEIGHTS_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_WEIGHTS_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_WEIGHTS_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_WEIGHTS_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_WEIGHTS_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_WEIGHTS_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_WEIGHTS_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_WEIGHTS_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WEIGHTS_0_WVALID : OUT STD_LOGIC;
        m_axi_WEIGHTS_0_WREADY : IN STD_LOGIC;
        m_axi_WEIGHTS_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_WEIGHTS_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WEIGHTS_0_WLAST : OUT STD_LOGIC;
        m_axi_WEIGHTS_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WEIGHTS_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WEIGHTS_0_ARVALID : OUT STD_LOGIC;
        m_axi_WEIGHTS_0_ARREADY : IN STD_LOGIC;
        m_axi_WEIGHTS_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_WEIGHTS_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WEIGHTS_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_WEIGHTS_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_WEIGHTS_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_WEIGHTS_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_WEIGHTS_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_WEIGHTS_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_WEIGHTS_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_WEIGHTS_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_WEIGHTS_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WEIGHTS_0_RVALID : IN STD_LOGIC;
        m_axi_WEIGHTS_0_RREADY : OUT STD_LOGIC;
        m_axi_WEIGHTS_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_WEIGHTS_0_RLAST : IN STD_LOGIC;
        m_axi_WEIGHTS_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WEIGHTS_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_WEIGHTS_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WEIGHTS_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_WEIGHTS_0_BVALID : IN STD_LOGIC;
        m_axi_WEIGHTS_0_BREADY : OUT STD_LOGIC;
        m_axi_WEIGHTS_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_WEIGHTS_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WEIGHTS_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        hidden_0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_0_ap_vld : OUT STD_LOGIC;
        W1 : IN STD_LOGIC_VECTOR (63 downto 0);
        hidden_31 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_31_ap_vld : OUT STD_LOGIC;
        hidden_30 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_30_ap_vld : OUT STD_LOGIC;
        hidden_29 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_29_ap_vld : OUT STD_LOGIC;
        hidden_28 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_28_ap_vld : OUT STD_LOGIC;
        hidden_27 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_27_ap_vld : OUT STD_LOGIC;
        hidden_26 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_26_ap_vld : OUT STD_LOGIC;
        hidden_25 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_25_ap_vld : OUT STD_LOGIC;
        hidden_24 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_24_ap_vld : OUT STD_LOGIC;
        hidden_23 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_23_ap_vld : OUT STD_LOGIC;
        hidden_22 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_22_ap_vld : OUT STD_LOGIC;
        hidden_21 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_21_ap_vld : OUT STD_LOGIC;
        hidden_20 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_20_ap_vld : OUT STD_LOGIC;
        hidden_19 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_19_ap_vld : OUT STD_LOGIC;
        hidden_18 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_18_ap_vld : OUT STD_LOGIC;
        hidden_17 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_17_ap_vld : OUT STD_LOGIC;
        hidden_16 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_16_ap_vld : OUT STD_LOGIC;
        hidden_15 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_15_ap_vld : OUT STD_LOGIC;
        hidden_14 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_14_ap_vld : OUT STD_LOGIC;
        hidden_13 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_13_ap_vld : OUT STD_LOGIC;
        hidden_12 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_12_ap_vld : OUT STD_LOGIC;
        hidden_11 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_11_ap_vld : OUT STD_LOGIC;
        hidden_10 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_10_ap_vld : OUT STD_LOGIC;
        hidden_9 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_9_ap_vld : OUT STD_LOGIC;
        hidden_8 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_8_ap_vld : OUT STD_LOGIC;
        hidden_7 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_7_ap_vld : OUT STD_LOGIC;
        hidden_6 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_6_ap_vld : OUT STD_LOGIC;
        hidden_5 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_5_ap_vld : OUT STD_LOGIC;
        hidden_4 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_4_ap_vld : OUT STD_LOGIC;
        hidden_3 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_3_ap_vld : OUT STD_LOGIC;
        hidden_2 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_2_ap_vld : OUT STD_LOGIC;
        hidden_1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        hidden_1_ap_vld : OUT STD_LOGIC;
        sext_ln41 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_1 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_2 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_3 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_4 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_5 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_6 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_7 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_8 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_9 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_10 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_11 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_12 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_13 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_14 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_15 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_16 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_17 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_18 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_19 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_20 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_21 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_22 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_23 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_24 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_25 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_26 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_27 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_28 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_29 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_30 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_31 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_32 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_33 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_34 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_35 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_36 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_37 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_38 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_39 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_40 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_41 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_42 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_43 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_44 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_45 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_46 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_47 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_48 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_49 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_50 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_51 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_52 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_53 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_54 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_55 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_56 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_57 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_58 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_59 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_60 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_61 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln41_62 : IN STD_LOGIC_VECTOR (1 downto 0);
        sext_ln36 : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;



begin
    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621 : component train_step_forwardHidden_Pipeline_VITIS_LOOP_36_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start,
        ap_done => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done,
        ap_idle => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_idle,
        ap_ready => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_ready,
        m_axi_WEIGHTS_0_AWVALID => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWVALID,
        m_axi_WEIGHTS_0_AWREADY => ap_const_logic_0,
        m_axi_WEIGHTS_0_AWADDR => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWADDR,
        m_axi_WEIGHTS_0_AWID => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWID,
        m_axi_WEIGHTS_0_AWLEN => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWLEN,
        m_axi_WEIGHTS_0_AWSIZE => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWSIZE,
        m_axi_WEIGHTS_0_AWBURST => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWBURST,
        m_axi_WEIGHTS_0_AWLOCK => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWLOCK,
        m_axi_WEIGHTS_0_AWCACHE => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWCACHE,
        m_axi_WEIGHTS_0_AWPROT => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWPROT,
        m_axi_WEIGHTS_0_AWQOS => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWQOS,
        m_axi_WEIGHTS_0_AWREGION => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWREGION,
        m_axi_WEIGHTS_0_AWUSER => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_AWUSER,
        m_axi_WEIGHTS_0_WVALID => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WVALID,
        m_axi_WEIGHTS_0_WREADY => ap_const_logic_0,
        m_axi_WEIGHTS_0_WDATA => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WDATA,
        m_axi_WEIGHTS_0_WSTRB => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WSTRB,
        m_axi_WEIGHTS_0_WLAST => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WLAST,
        m_axi_WEIGHTS_0_WID => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WID,
        m_axi_WEIGHTS_0_WUSER => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_WUSER,
        m_axi_WEIGHTS_0_ARVALID => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARVALID,
        m_axi_WEIGHTS_0_ARREADY => m_axi_WEIGHTS_0_ARREADY,
        m_axi_WEIGHTS_0_ARADDR => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARADDR,
        m_axi_WEIGHTS_0_ARID => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARID,
        m_axi_WEIGHTS_0_ARLEN => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARLEN,
        m_axi_WEIGHTS_0_ARSIZE => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARSIZE,
        m_axi_WEIGHTS_0_ARBURST => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARBURST,
        m_axi_WEIGHTS_0_ARLOCK => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARLOCK,
        m_axi_WEIGHTS_0_ARCACHE => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARCACHE,
        m_axi_WEIGHTS_0_ARPROT => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARPROT,
        m_axi_WEIGHTS_0_ARQOS => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARQOS,
        m_axi_WEIGHTS_0_ARREGION => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARREGION,
        m_axi_WEIGHTS_0_ARUSER => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARUSER,
        m_axi_WEIGHTS_0_RVALID => m_axi_WEIGHTS_0_RVALID,
        m_axi_WEIGHTS_0_RREADY => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_RREADY,
        m_axi_WEIGHTS_0_RDATA => m_axi_WEIGHTS_0_RDATA,
        m_axi_WEIGHTS_0_RLAST => m_axi_WEIGHTS_0_RLAST,
        m_axi_WEIGHTS_0_RID => m_axi_WEIGHTS_0_RID,
        m_axi_WEIGHTS_0_RFIFONUM => m_axi_WEIGHTS_0_RFIFONUM,
        m_axi_WEIGHTS_0_RUSER => m_axi_WEIGHTS_0_RUSER,
        m_axi_WEIGHTS_0_RRESP => m_axi_WEIGHTS_0_RRESP,
        m_axi_WEIGHTS_0_BVALID => ap_const_logic_0,
        m_axi_WEIGHTS_0_BREADY => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_BREADY,
        m_axi_WEIGHTS_0_BRESP => ap_const_lv2_0,
        m_axi_WEIGHTS_0_BID => ap_const_lv1_0,
        m_axi_WEIGHTS_0_BUSER => ap_const_lv1_0,
        hidden_0 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0,
        hidden_0_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0_ap_vld,
        W1 => W1,
        hidden_31 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31,
        hidden_31_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31_ap_vld,
        hidden_30 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30,
        hidden_30_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30_ap_vld,
        hidden_29 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29,
        hidden_29_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29_ap_vld,
        hidden_28 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28,
        hidden_28_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28_ap_vld,
        hidden_27 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27,
        hidden_27_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27_ap_vld,
        hidden_26 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26,
        hidden_26_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26_ap_vld,
        hidden_25 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25,
        hidden_25_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25_ap_vld,
        hidden_24 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24,
        hidden_24_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24_ap_vld,
        hidden_23 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23,
        hidden_23_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23_ap_vld,
        hidden_22 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22,
        hidden_22_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22_ap_vld,
        hidden_21 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21,
        hidden_21_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21_ap_vld,
        hidden_20 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20,
        hidden_20_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20_ap_vld,
        hidden_19 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19,
        hidden_19_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19_ap_vld,
        hidden_18 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18,
        hidden_18_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18_ap_vld,
        hidden_17 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17,
        hidden_17_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17_ap_vld,
        hidden_16 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16,
        hidden_16_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16_ap_vld,
        hidden_15 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15,
        hidden_15_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15_ap_vld,
        hidden_14 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14,
        hidden_14_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14_ap_vld,
        hidden_13 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13,
        hidden_13_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13_ap_vld,
        hidden_12 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12,
        hidden_12_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12_ap_vld,
        hidden_11 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11,
        hidden_11_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11_ap_vld,
        hidden_10 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10,
        hidden_10_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10_ap_vld,
        hidden_9 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9,
        hidden_9_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9_ap_vld,
        hidden_8 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8,
        hidden_8_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8_ap_vld,
        hidden_7 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7,
        hidden_7_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7_ap_vld,
        hidden_6 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6,
        hidden_6_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6_ap_vld,
        hidden_5 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5,
        hidden_5_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5_ap_vld,
        hidden_4 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4,
        hidden_4_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4_ap_vld,
        hidden_3 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3,
        hidden_3_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3_ap_vld,
        hidden_2 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2,
        hidden_2_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2_ap_vld,
        hidden_1 => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1,
        hidden_1_ap_vld => grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1_ap_vld,
        sext_ln41 => input_0_val,
        sext_ln41_1 => input_1_val,
        sext_ln41_2 => input_2_val,
        sext_ln41_3 => input_3_val,
        sext_ln41_4 => input_4_val,
        sext_ln41_5 => input_5_val,
        sext_ln41_6 => input_6_val,
        sext_ln41_7 => input_7_val,
        sext_ln41_8 => input_8_val,
        sext_ln41_9 => input_9_val,
        sext_ln41_10 => input_10_val,
        sext_ln41_11 => input_11_val,
        sext_ln41_12 => input_12_val,
        sext_ln41_13 => input_13_val,
        sext_ln41_14 => input_14_val,
        sext_ln41_15 => input_15_val,
        sext_ln41_16 => input_16_val,
        sext_ln41_17 => input_17_val,
        sext_ln41_18 => input_18_val,
        sext_ln41_19 => input_19_val,
        sext_ln41_20 => input_20_val,
        sext_ln41_21 => input_21_val,
        sext_ln41_22 => input_22_val,
        sext_ln41_23 => input_23_val,
        sext_ln41_24 => input_24_val,
        sext_ln41_25 => input_25_val,
        sext_ln41_26 => input_26_val,
        sext_ln41_27 => input_27_val,
        sext_ln41_28 => input_28_val,
        sext_ln41_29 => input_29_val,
        sext_ln41_30 => input_30_val,
        sext_ln41_31 => input_31_val,
        sext_ln41_32 => input_32_val,
        sext_ln41_33 => input_33_val,
        sext_ln41_34 => input_34_val,
        sext_ln41_35 => input_35_val,
        sext_ln41_36 => input_36_val,
        sext_ln41_37 => input_37_val,
        sext_ln41_38 => input_38_val,
        sext_ln41_39 => input_39_val,
        sext_ln41_40 => input_40_val,
        sext_ln41_41 => input_41_val,
        sext_ln41_42 => input_42_val,
        sext_ln41_43 => input_43_val,
        sext_ln41_44 => input_44_val,
        sext_ln41_45 => input_45_val,
        sext_ln41_46 => input_46_val,
        sext_ln41_47 => input_47_val,
        sext_ln41_48 => input_48_val,
        sext_ln41_49 => input_49_val,
        sext_ln41_50 => input_50_val,
        sext_ln41_51 => input_51_val,
        sext_ln41_52 => input_52_val,
        sext_ln41_53 => input_53_val,
        sext_ln41_54 => input_54_val,
        sext_ln41_55 => input_55_val,
        sext_ln41_56 => input_56_val,
        sext_ln41_57 => input_57_val,
        sext_ln41_58 => input_58_val,
        sext_ln41_59 => input_59_val,
        sext_ln41_60 => input_60_val,
        sext_ln41_61 => input_61_val,
        sext_ln41_62 => input_62_val,
        sext_ln36 => input_63_val);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_ready = ap_const_logic_1)) then 
                    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_0_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_10_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_11_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_12_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_13_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_14_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_15_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_16_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_17_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_18_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_19_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_1_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_20_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_21_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_22_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_23_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_24_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_25_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_26_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_27_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_28_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_29_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_2_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_30_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_31_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_3_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_4_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_5_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_6_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_7_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_8_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                hidden_9_reg <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, m_axi_WEIGHTS_0_ARREADY, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done, ap_CS_fsm_state10)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((m_axi_WEIGHTS_0_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;

    WEIGHTS_blk_n_AR_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_WEIGHTS_0_ARREADY)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            WEIGHTS_blk_n_AR <= m_axi_WEIGHTS_0_ARREADY;
        else 
            WEIGHTS_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done)
    begin
        if ((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, m_axi_WEIGHTS_0_ARREADY)
    begin
        if (((m_axi_WEIGHTS_0_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done, ap_CS_fsm_state10)
    begin
        if ((((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done, ap_CS_fsm_state10)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_ap_start_reg;

    hidden_0_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0_ap_vld, hidden_0_reg, ap_CS_fsm_state10)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_0 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0;
        else 
            hidden_0 <= hidden_0_reg;
        end if; 
    end process;

    hidden_0_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_0_ap_vld;

    hidden_1_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1_ap_vld, ap_CS_fsm_state10, hidden_1_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_1 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1;
        else 
            hidden_1 <= hidden_1_reg;
        end if; 
    end process;


    hidden_10_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10_ap_vld, ap_CS_fsm_state10, hidden_10_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_10 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10;
        else 
            hidden_10 <= hidden_10_reg;
        end if; 
    end process;

    hidden_10_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_10_ap_vld;

    hidden_11_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11_ap_vld, ap_CS_fsm_state10, hidden_11_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_11 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11;
        else 
            hidden_11 <= hidden_11_reg;
        end if; 
    end process;

    hidden_11_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_11_ap_vld;

    hidden_12_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12_ap_vld, ap_CS_fsm_state10, hidden_12_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_12 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12;
        else 
            hidden_12 <= hidden_12_reg;
        end if; 
    end process;

    hidden_12_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_12_ap_vld;

    hidden_13_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13_ap_vld, ap_CS_fsm_state10, hidden_13_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_13 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13;
        else 
            hidden_13 <= hidden_13_reg;
        end if; 
    end process;

    hidden_13_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_13_ap_vld;

    hidden_14_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14_ap_vld, ap_CS_fsm_state10, hidden_14_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_14 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14;
        else 
            hidden_14 <= hidden_14_reg;
        end if; 
    end process;

    hidden_14_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_14_ap_vld;

    hidden_15_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15_ap_vld, ap_CS_fsm_state10, hidden_15_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_15 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15;
        else 
            hidden_15 <= hidden_15_reg;
        end if; 
    end process;

    hidden_15_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_15_ap_vld;

    hidden_16_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16_ap_vld, ap_CS_fsm_state10, hidden_16_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_16 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16;
        else 
            hidden_16 <= hidden_16_reg;
        end if; 
    end process;

    hidden_16_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_16_ap_vld;

    hidden_17_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17_ap_vld, ap_CS_fsm_state10, hidden_17_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_17 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17;
        else 
            hidden_17 <= hidden_17_reg;
        end if; 
    end process;

    hidden_17_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_17_ap_vld;

    hidden_18_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18_ap_vld, ap_CS_fsm_state10, hidden_18_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_18 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18;
        else 
            hidden_18 <= hidden_18_reg;
        end if; 
    end process;

    hidden_18_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_18_ap_vld;

    hidden_19_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19_ap_vld, ap_CS_fsm_state10, hidden_19_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_19 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19;
        else 
            hidden_19 <= hidden_19_reg;
        end if; 
    end process;

    hidden_19_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_19_ap_vld;
    hidden_1_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_1_ap_vld;

    hidden_2_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2_ap_vld, ap_CS_fsm_state10, hidden_2_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_2 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2;
        else 
            hidden_2 <= hidden_2_reg;
        end if; 
    end process;


    hidden_20_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20_ap_vld, ap_CS_fsm_state10, hidden_20_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_20 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20;
        else 
            hidden_20 <= hidden_20_reg;
        end if; 
    end process;

    hidden_20_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_20_ap_vld;

    hidden_21_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21_ap_vld, ap_CS_fsm_state10, hidden_21_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_21 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21;
        else 
            hidden_21 <= hidden_21_reg;
        end if; 
    end process;

    hidden_21_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_21_ap_vld;

    hidden_22_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22_ap_vld, ap_CS_fsm_state10, hidden_22_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_22 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22;
        else 
            hidden_22 <= hidden_22_reg;
        end if; 
    end process;

    hidden_22_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_22_ap_vld;

    hidden_23_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23_ap_vld, ap_CS_fsm_state10, hidden_23_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_23 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23;
        else 
            hidden_23 <= hidden_23_reg;
        end if; 
    end process;

    hidden_23_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_23_ap_vld;

    hidden_24_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24_ap_vld, ap_CS_fsm_state10, hidden_24_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_24 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24;
        else 
            hidden_24 <= hidden_24_reg;
        end if; 
    end process;

    hidden_24_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_24_ap_vld;

    hidden_25_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25_ap_vld, ap_CS_fsm_state10, hidden_25_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_25 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25;
        else 
            hidden_25 <= hidden_25_reg;
        end if; 
    end process;

    hidden_25_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_25_ap_vld;

    hidden_26_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26_ap_vld, ap_CS_fsm_state10, hidden_26_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_26 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26;
        else 
            hidden_26 <= hidden_26_reg;
        end if; 
    end process;

    hidden_26_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_26_ap_vld;

    hidden_27_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27_ap_vld, ap_CS_fsm_state10, hidden_27_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_27 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27;
        else 
            hidden_27 <= hidden_27_reg;
        end if; 
    end process;

    hidden_27_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_27_ap_vld;

    hidden_28_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28_ap_vld, ap_CS_fsm_state10, hidden_28_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_28 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28;
        else 
            hidden_28 <= hidden_28_reg;
        end if; 
    end process;

    hidden_28_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_28_ap_vld;

    hidden_29_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29_ap_vld, ap_CS_fsm_state10, hidden_29_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_29 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29;
        else 
            hidden_29 <= hidden_29_reg;
        end if; 
    end process;

    hidden_29_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_29_ap_vld;
    hidden_2_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_2_ap_vld;

    hidden_3_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3_ap_vld, ap_CS_fsm_state10, hidden_3_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_3 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3;
        else 
            hidden_3 <= hidden_3_reg;
        end if; 
    end process;


    hidden_30_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30_ap_vld, ap_CS_fsm_state10, hidden_30_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_30 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30;
        else 
            hidden_30 <= hidden_30_reg;
        end if; 
    end process;

    hidden_30_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_30_ap_vld;

    hidden_31_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31_ap_vld, ap_CS_fsm_state10, hidden_31_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_31 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31;
        else 
            hidden_31 <= hidden_31_reg;
        end if; 
    end process;

    hidden_31_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_31_ap_vld;
    hidden_3_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_3_ap_vld;

    hidden_4_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4_ap_vld, ap_CS_fsm_state10, hidden_4_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_4 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4;
        else 
            hidden_4 <= hidden_4_reg;
        end if; 
    end process;

    hidden_4_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_4_ap_vld;

    hidden_5_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5_ap_vld, ap_CS_fsm_state10, hidden_5_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_5 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5;
        else 
            hidden_5 <= hidden_5_reg;
        end if; 
    end process;

    hidden_5_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_5_ap_vld;

    hidden_6_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6_ap_vld, ap_CS_fsm_state10, hidden_6_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_6 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6;
        else 
            hidden_6 <= hidden_6_reg;
        end if; 
    end process;

    hidden_6_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_6_ap_vld;

    hidden_7_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7_ap_vld, ap_CS_fsm_state10, hidden_7_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_7 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7;
        else 
            hidden_7 <= hidden_7_reg;
        end if; 
    end process;

    hidden_7_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_7_ap_vld;

    hidden_8_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8_ap_vld, ap_CS_fsm_state10, hidden_8_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_8 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8;
        else 
            hidden_8 <= hidden_8_reg;
        end if; 
    end process;

    hidden_8_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_8_ap_vld;

    hidden_9_assign_proc : process(grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9_ap_vld, ap_CS_fsm_state10, hidden_9_reg)
    begin
        if (((grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            hidden_9 <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9;
        else 
            hidden_9 <= hidden_9_reg;
        end if; 
    end process;

    hidden_9_ap_vld <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_hidden_9_ap_vld;

    m_axi_WEIGHTS_0_ARADDR_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_WEIGHTS_0_ARREADY, W1, ap_CS_fsm_state9, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARADDR, ap_CS_fsm_state10)
    begin
        if ((not(((m_axi_WEIGHTS_0_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_WEIGHTS_0_ARADDR <= W1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_WEIGHTS_0_ARADDR <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARADDR;
        else 
            m_axi_WEIGHTS_0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_WEIGHTS_0_ARBURST_assign_proc : process(ap_CS_fsm_state9, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARBURST, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_WEIGHTS_0_ARBURST <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARBURST;
        else 
            m_axi_WEIGHTS_0_ARBURST <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_WEIGHTS_0_ARCACHE_assign_proc : process(ap_CS_fsm_state9, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARCACHE, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_WEIGHTS_0_ARCACHE <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARCACHE;
        else 
            m_axi_WEIGHTS_0_ARCACHE <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_WEIGHTS_0_ARID_assign_proc : process(ap_CS_fsm_state9, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARID, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_WEIGHTS_0_ARID <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARID;
        else 
            m_axi_WEIGHTS_0_ARID <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_WEIGHTS_0_ARLEN_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_WEIGHTS_0_ARREADY, ap_CS_fsm_state9, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARLEN, ap_CS_fsm_state10)
    begin
        if ((not(((m_axi_WEIGHTS_0_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_WEIGHTS_0_ARLEN <= ap_const_lv64_800(32 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_WEIGHTS_0_ARLEN <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARLEN;
        else 
            m_axi_WEIGHTS_0_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_WEIGHTS_0_ARLOCK_assign_proc : process(ap_CS_fsm_state9, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARLOCK, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_WEIGHTS_0_ARLOCK <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARLOCK;
        else 
            m_axi_WEIGHTS_0_ARLOCK <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_WEIGHTS_0_ARPROT_assign_proc : process(ap_CS_fsm_state9, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARPROT, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_WEIGHTS_0_ARPROT <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARPROT;
        else 
            m_axi_WEIGHTS_0_ARPROT <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_WEIGHTS_0_ARQOS_assign_proc : process(ap_CS_fsm_state9, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARQOS, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_WEIGHTS_0_ARQOS <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARQOS;
        else 
            m_axi_WEIGHTS_0_ARQOS <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_WEIGHTS_0_ARREGION_assign_proc : process(ap_CS_fsm_state9, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARREGION, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_WEIGHTS_0_ARREGION <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARREGION;
        else 
            m_axi_WEIGHTS_0_ARREGION <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_WEIGHTS_0_ARSIZE_assign_proc : process(ap_CS_fsm_state9, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARSIZE, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_WEIGHTS_0_ARSIZE <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARSIZE;
        else 
            m_axi_WEIGHTS_0_ARSIZE <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_WEIGHTS_0_ARUSER_assign_proc : process(ap_CS_fsm_state9, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARUSER, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_WEIGHTS_0_ARUSER <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARUSER;
        else 
            m_axi_WEIGHTS_0_ARUSER <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_WEIGHTS_0_ARVALID_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_WEIGHTS_0_ARREADY, ap_CS_fsm_state9, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARVALID, ap_CS_fsm_state10)
    begin
        if ((not(((m_axi_WEIGHTS_0_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_WEIGHTS_0_ARVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_WEIGHTS_0_ARVALID <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_ARVALID;
        else 
            m_axi_WEIGHTS_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_WEIGHTS_0_AWADDR <= ap_const_lv64_0;
    m_axi_WEIGHTS_0_AWBURST <= ap_const_lv2_0;
    m_axi_WEIGHTS_0_AWCACHE <= ap_const_lv4_0;
    m_axi_WEIGHTS_0_AWID <= ap_const_lv1_0;
    m_axi_WEIGHTS_0_AWLEN <= ap_const_lv32_0;
    m_axi_WEIGHTS_0_AWLOCK <= ap_const_lv2_0;
    m_axi_WEIGHTS_0_AWPROT <= ap_const_lv3_0;
    m_axi_WEIGHTS_0_AWQOS <= ap_const_lv4_0;
    m_axi_WEIGHTS_0_AWREGION <= ap_const_lv4_0;
    m_axi_WEIGHTS_0_AWSIZE <= ap_const_lv3_0;
    m_axi_WEIGHTS_0_AWUSER <= ap_const_lv1_0;
    m_axi_WEIGHTS_0_AWVALID <= ap_const_logic_0;
    m_axi_WEIGHTS_0_BREADY <= ap_const_logic_0;

    m_axi_WEIGHTS_0_RREADY_assign_proc : process(ap_CS_fsm_state9, grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_RREADY, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_WEIGHTS_0_RREADY <= grp_forwardHidden_Pipeline_VITIS_LOOP_36_1_fu_621_m_axi_WEIGHTS_0_RREADY;
        else 
            m_axi_WEIGHTS_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_WEIGHTS_0_WDATA <= ap_const_lv8_0;
    m_axi_WEIGHTS_0_WID <= ap_const_lv1_0;
    m_axi_WEIGHTS_0_WLAST <= ap_const_logic_0;
    m_axi_WEIGHTS_0_WSTRB <= ap_const_lv1_0;
    m_axi_WEIGHTS_0_WUSER <= ap_const_lv1_0;
    m_axi_WEIGHTS_0_WVALID <= ap_const_logic_0;
end behav;
