#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("leds_port", 4, hls_out, 18, "ap_vld", "out_data", 1),
	Port_Property("leds_port_ap_vld", 1, hls_out, 18, "ap_vld", "out_vld", 1),
	Port_Property("W1_out_address0", 5, hls_out, 19, "ap_memory", "mem_address", 1),
	Port_Property("W1_out_ce0", 1, hls_out, 19, "ap_memory", "mem_ce", 1),
	Port_Property("W1_out_we0", 1, hls_out, 19, "ap_memory", "mem_we", 1),
	Port_Property("W1_out_d0", 8, hls_out, 19, "ap_memory", "mem_din", 1),
	Port_Property("W1_out_address1", 5, hls_out, 19, "ap_memory", "MemPortADDR2", 1),
	Port_Property("W1_out_ce1", 1, hls_out, 19, "ap_memory", "MemPortCE2", 1),
	Port_Property("W1_out_we1", 1, hls_out, 19, "ap_memory", "MemPortWE2", 1),
	Port_Property("W1_out_d1", 8, hls_out, 19, "ap_memory", "MemPortDIN2", 1),
	Port_Property("W2_out_address0", 2, hls_out, 20, "ap_memory", "mem_address", 1),
	Port_Property("W2_out_ce0", 1, hls_out, 20, "ap_memory", "mem_ce", 1),
	Port_Property("W2_out_we0", 1, hls_out, 20, "ap_memory", "mem_we", 1),
	Port_Property("W2_out_d0", 8, hls_out, 20, "ap_memory", "mem_din", 1),
	Port_Property("s_axi_CTRL_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_AWADDR", 8, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_ARADDR", 8, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "train_step";
